name: Android
on: [push]

jobs:
  build:
    name: Build APK
    runs-on: macOS-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradle version
        run: gradle -v
      - name: Set up gradle.properties
        run: echo "$GRADLE_PROPERTIES" | base64 -D > ~/.gradle/gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      - name: Set up android keystore
        working-directory: MeinsApp/android/app
        run: |
          mkdir ~/.play
          echo "$ANDROID_KEYSTORE" | base64 -D > release.keystore
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      - name: Set up playstore
        run: echo "$JSON_KEY_FILE" | base64 -D > ~/.play/api-8047501467075210695-634125-d6886135229e.json
        env:
          JSON_KEY_FILE: ${{ secrets.JSON_KEY_FILE }}
      - name: Debug app folder
        working-directory: MeinsApp/android/app
        run: ls
      - name: Debug up android keystore
        run: |
          cd ~/.android
          pwd
          ls -la
      - uses: malinskiy/action-android/install-sdk@release/0.0.2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Update fastlane
        working-directory: MeinsApp/android
        run: fastlane update_fastlane
      - name: Install yarn
        run: npm install -g yarn
      - name: Install shadow-cljs
        run: npm install -g shadow-cljs
      - name: Install react-native-cli
        run: npm install -g react-native-cli
      - name: Install cli-platform-android
        working-directory: MeinsApp
        run: npm i @react-native-community/cli-platform-android
      - name: Build JS
        working-directory: MeinsApp
        run: make npm-deps cljs
      - name: Create app bundle
        working-directory: MeinsApp/android
        run: fastlane bundle
        env:
          RN_BG_GEO_KEY: ${{ secrets.RN_BG_GEO_KEY }}
      - uses: actions/upload-artifact@master
        with:
          name: release-aab
          path: MeinsApp/android/app/build/outputs/bundle/release/app-release.aab
      - name: Playstore init
        working-directory: MeinsApp/android
        run: fastlane supply init
      - name: Playstore upload
        working-directory: MeinsApp/android
        run: fastlane supply --aab app/build/outputs/bundle/release/app-release.aab --track internal
