name: Flutter Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Flutter Test on macOS
    permissions:
      contents: read
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Install mpv
        run: brew install mpv
      - name: Get dependencies
        run: flutter pub get
      - name: Get pod dependencies
        run: pod install
        working-directory: macos
      - name: Run Flutter tests
        run: flutter test --coverage
      - uses: codecov/codecov-action@v5
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: matthiasn/lotti
