include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    document_ignores: false
    avoid_catches_without_on_clauses: false
    discarded_futures: false
    require_trailing_commas: false

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore
  language:
    strict-raw-types: true
  plugins:
    - custom_lint

custom_lint:
  rules:
    # Disable noisy rules that don't add value
    - avoid_public_notifier_properties: false
    - scoped_providers_should_specify_dependencies: false
    - avoid_manual_providers_as_generated_provider_dependency: false
    - missing_provider_scope: false
    - no_get_it_in_sync: false  # Also disable getIt warnings in sync module
