image: Visual Studio 2019

platform:
  - x64

configuration:
  - Release

install:
  - choco install make
  - cmd: |
      choco install openjdk -params "source=false"
      refreshenv
  - ps: Install-Product node 12 x64

  # these need to have a line in between because of Windows line endings
  - ps: >-
      New-Item c:\scripts -type directory

      $env:Path += ";C:\scripts"

      Invoke-WebRequest -Uri https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat -OutFile "C:\scripts\lein.bat"

      lein self-install

  - npm install -g yarn
  - npm install -g shadow-cljs
  - npm install -g electron-rebuild

test_script:
  - cmd: make release

# Don't actually build (MSBuild).
build: off