targets:
  $default:
    builders:

      drift_dev:
        options:
          generate_connect_constructor: true
          sql:
            dialect: sqlite
            options:
              modules:
                - fts5
      flutter_gen:
        options:
          synthetic_package: false