coverage:
  status:
    project:
      default:
        threshold: 0.1%
    patch:
      default:
        target: 93%
ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/l10n/*.dart"
  - "**/widgetbook/**"
