arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: missing_translations.txt
preferred-supported-locales: [de, en]
arb-translate-api-key: AIzaSyAPF64A2myHUbkWHi391R3-A-gXprqjPdQ
arb-translate-model-provider: gemini
arb-translate-model: gemini-1.5-pro
