name: lotti
description: Achieve your goals and keep your data private with Lotti.
publish_to: 'none'
version: 0.9.629+3111

msix_config:
  display_name: LottiApp
  publisher_display_name: Nehlsen EDV Beratung GmbH
  publisher: CN=ED722F95-3F7E-428E-A642-9B9C121815D1
  identity_name: NehlsenEDVBeratungGmbH.LottiApp
  capabilities: internetClient, location, microphone
  languages: en-us, de-de, ro-ro
  install_certificate: false
  sign_msix: false
  logo_path: .\assets\icon\app_icon_1024.png

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  arb_utils: ^0.8.3
  audio_video_progress_bar: ^2.0.1
  auto_size_text: ^3.0.0
  beamer: ^1.5.2
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  cached_network_image: ^3.2.0
  calendar_view: ^1.2.0
  collection: ^1.18.0
  connectivity_plus: ^6.1.2
  crypto: ^3.0.1
  dart_geohash: ^2.0.1
  delta_markdown:
    git:
      url: https://github.com/matthiasn/delta_markdown.git
      ref: 131dbc1
  desktop_drop: ^0.6.0
  device_info_plus: ^11.0.0
  drift: ^2.21.0
  easy_debounce: ^2.0.2+1
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  exif: ^3.0.1
  extended_sliver: ^2.1.3
  fl_chart: ^1.0.0
  flex_color_scheme: ^8.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^9.0.0
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^10.0.1
  flutter_image_compress: ^2.0.3
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^19.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.0.0
  flutter_olm: ^2.0.0
  flutter_openssl_crypto: ^0.5.0

  #flutter_quill: ^11.0.0
  flutter_quill:
    git:
      url: https://github.com/theniceboy/flutter-quill
      ref: 5ff5967

  flutter_quill_extensions: ^11.0.0
  flutter_rating: ^2.0.2
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  flutter_vodozemac: ^0.2.2
  form_builder_validators: ^11.0.0
  formz: ^0.8.0
  freezed_annotation: ^2.0.3
  geoclue: ^0.1.0
  get_it: ^8.0.2
  glass_kit: ^4.0.1
  google_fonts: ^6.1.0
  gpt_markdown: ^1.0.20
  graphic: ^2.3.0
  health: ^13.1.0
  hotkey_manager: ^0.2.0
  http: ^1.2.0
  infinite_scroll_pagination: ^5.0.0
  intersperse: ^2.0.0
  intl: ^0.20.2
  ionicons: ^0.2.2
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  location: ^8.0.0
  material_design_icons_flutter: ^7.0.7096
  matrix: ^1.0.0
  media_kit: ^1.0.2
  media_kit_libs_android_audio: ^1.0.3
  media_kit_libs_ios_audio: ^1.0.4
  media_kit_libs_linux: ^1.0.2
  media_kit_libs_macos_audio: ^1.0.5
  media_kit_libs_windows_audio: ^1.0.3
  media_kit_native_event_loop: ^1.0.3
  mobile_scanner: ^7.0.0
  mocktail: ^1.0.0
  multi_select_flutter: ^4.0.0
  ollama: ^1.0.4
  openai_dart: ^0.5.0
  package_info_plus: ^8.0.0
  path: ^1.8.1
  path_provider: ^2.0.12
  permission_handler: ^12.0.0+1
  photo_manager: ^3.1.1
  photo_view: ^0.15.0
  pie_chart: ^5.3.2
  qr_flutter: ^4.0.0
  quiver: ^3.2.1
  radial_button: ^1.0.1
  record: ^6.0.0
  research_package:
    git:
      url: https://github.com/matthiasn/research.package
      ref: fc229b9d
  riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  riverpod_lint: ^2.3.10
  rxdart: ^0.28.0
  share_plus: ^11.0.0
  showcaseview: ^4.0.1
  siri_wave: ^2.3.0
  sqflite: ^2.0.1
  sqflite_common_ffi: ^2.3.3
  sqlite3: ^2.4.5
  sqlite3_flutter_libs: ^0.5.15
  super_clipboard: ^0.9.1
  super_drag_and_drop: ^0.9.1
  timezone: ^0.10.0
  tinycolor2: ^3.0.0
  url_launcher: ^6.1.2
  uuid: ^4.3.3
  vector_math: any
  visibility_detector: ^0.4.0+2
  vodozemac: ^0.2.0
  wechat_assets_picker: ^9.0.0
  widgetbook: ^3.7.1
  window_manager: ^0.5.0
  wolt_modal_sheet: ^0.11.0

dependency_overrides:
  analyzer_plugin: ^0.13.1
  flutter_quill:
    git:
      url: https://github.com/theniceboy/flutter-quill
      ref: 5ff5967
  get_it: ^8.0.2
  intl: ^0.20.2
  rxdart: ^0.28.0

dev_dependencies:
  analyzer: ^7.3.0
  archive: ^3.3.0
  build_runner: ^2.3.0
  dart_style: ^3.0.1
  drift_dev: ^2.16.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  glados: ^1.1.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.0.0
  msix: ^3.7.0
  path_provider_platform_interface: any
  plugin_platform_interface: any
  riverpod_generator: ^2.4.0
  very_good_analysis: ^8.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon_1024.png"
  image_path_ios: "assets/icon/app_icon_1024_square.png"
  macos:
    generate: true
    image_path: "assets/icon/app_icon_1024_mac.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon_1024.png"
    icon_size: 256

analyzer:
  plugins:
    - drift

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata/Inconsolata-Regular.ttf
    - family: InclusiveSans
      fonts:
        - asset: assets/fonts/InclusiveSans/InclusiveSans-Regular.ttf

  assets:
    - assets/icons/
    - assets/lang/
    - assets/sqlite/
    # from https://www.iconfinder.com/paomedia
    - assets/images/map/299087_marker_map_icon.png
    # from https://www.iconfinder.com/recepkutuk
    - assets/images/map/728975_location_map_marker_pin_place_icon.png
    - assets/images/tutorial/

flutter_native_splash:
  color: "#333333"
