name: lotti
description: Achieve your goals and keep your data private with Lotti.
publish_to: 'none'
version: 0.9.354+2139

msix_config:
  display_name: LottiApp
  publisher_display_name: Nehlsen EDV Beratung GmbH
  publisher: CN=ED722F95-3F7E-428E-A642-9B9C121815D1
  identity_name: NehlsenEDVBeratungGmbH.LottiApp
  capabilities: internetClient, location, microphone
  languages: en-us, de-de, ro-ro
  install_certificate: false
  sign_msix: false
  logo_path: .\assets\icon\app_icon_1024.png

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  arb_utils: ^0.3.0
  audio_video_progress_bar: ^1.0.0
  auto_size_text: ^3.0.0
  beamer: ^1.5.2
  bloc: ^8.0.1
  bloc_test: ^9.0.1
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  charts_flutter: ^0.12.0
  collection: ^1.17.0
  connectivity_plus: ^4.0.0
  crypto: ^3.0.1
  cryptography: ^2.0.2
  cupertino_icons: ^1.0.5
  dart_geohash: ^2.0.1

  delta_markdown:
    git:
      url: https://github.com/matthiasn/delta_markdown.git
      ref: 1beb378

  device_info_plus: ^9.0.0
  drift: ^2.8.0
  easy_debounce: ^2.0.2+1
  encrypt: ^5.0.1
  enough_mail: ^2.0.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  exif: ^3.0.1

  ffmpeg_kit_flutter: ^5.1.0
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.0
  flutter_colorpicker: ^1.0.3
  flutter_download_manager: ^0.5.5
  flutter_fadein: ^2.0.0
  flutter_fgbg: ^0.2.0
  flutter_form_builder: ^8.0.0

  flutter_health_fit:
    git:
      url: https://github.com/matthiasn/flutter_health_fit.git
      ref: 37afbc9

  flutter_image_compress: ^1.1.0
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^13.0.0

  flutter_localizations:
    sdk: flutter

  flutter_map: ^3.1.0
  flutter_markdown: ^0.6.9+1
  flutter_native_timezone: ^2.0.0
  flutter_quill: ^7.1.18
  flutter_secure_storage: ^8.0.0
  flutter_sliding_tutorial: ^2.0.0
  flutter_svg: ^2.0.0
  form_builder_validators: ^8.1.1
  freezed_annotation: ^2.0.3
  geoclue: ^0.1.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3

  #health: ^4.4.0
  health:
    git:
      url: https://github.com/matthiasn/flutter-plugins
      path: packages/health
      ref: 1fcaf9c

  hotkey_manager: ^0.1.6
  infinite_scroll_pagination: ^3.2.0
  intersperse: ^2.0.0
  intl: ^0.18.0
  jiffy: ^6.1.0
  json_annotation: ^4.8.1
  latlong2: ^0.8.1
  location: ^4.3.0
  lottie: ^2.2.0
  material_design_icons_flutter: ^6.0.7096
  media_kit: ^0.0.7
  media_kit_libs_android_audio: ^1.0.3
  media_kit_libs_ios_audio: ^1.0.4
  media_kit_libs_linux: ^1.0.2
  media_kit_libs_macos_audio: ^1.0.5
  media_kit_libs_windows_audio: ^1.0.3
  media_kit_native_event_loop: ^1.0.3
  meta: ^1.8.0
  multi_select_flutter: ^4.0.0
  package_info_plus: ^4.0.0
  path: ^1.8.1
  path_provider: ^2.0.12
  permission_handler: ^10.0.0
  photo_view: ^0.14.0
  pie_chart: ^5.3.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  quiver: ^3.2.1
  radial_button:
    git:
      url: https://github.com/redinterface/radial_button
      ref: 8140fcf

  random_password_generator: ^0.2.1
  record: ^4.4.4
  research_package: ^1.3.1
  retry: ^3.1.0
  rxdart: ^0.27.7
  share_plus: ^7.0.0
  sqflite: ^2.0.1
  sqlite3_flutter_libs: ^0.5.2
  syncfusion_flutter_calendar: ^21.1.38
  syncfusion_flutter_datepicker: ^21.1.38
  timezone: ^0.9.1
  tinycolor2: ^3.0.0
  tuple: ^2.0.0
  url_launcher: ^6.1.2
  uuid: ^3.0.4
  vector_graphics: 1.1.5
  visibility_detector: ^0.4.0+2
  wechat_assets_picker: ^8.4.1
  week_of_year: ^2.0.0
  window_manager: ^0.3.0

dependency_overrides:
  device_info_plus: ^9.0.0
  image: ^4.0.13
  intl: ^0.18.0
  rxdart: ^0.27.1

dev_dependencies:
  analyzer: ^5.12.0
  archive: ^3.3.0
  build_runner: ^2.3.0
  dart_code_metrics: ^5.5.0
  drift_dev: ^2.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  glados: ^1.1.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  msix: ^3.7.0
  very_good_analysis: ^5.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon_1024.png"
  image_path_ios: "assets/icon/app_icon_1024_square.png"
  macos:
    generate: true
    image_path: "assets/icon/app_icon_1024_mac.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon_1024.png"
    icon_size: 256

analyzer:
  plugins:
    - drift

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/sqlite/
    # from https://www.iconfinder.com/paomedia
    - assets/images/map/299087_marker_map_icon.png
    # from https://www.iconfinder.com/recepkutuk
    - assets/images/map/728975_location_map_marker_pin_place_icon.png
    - assets/images/tutorial/
    - assets/lottiefiles/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-ExtraLight.ttf
        - asset: assets/fonts/Oswald-Light.ttf
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Medium.ttf
        - asset: assets/fonts/Oswald-SemiBold.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata/Inconsolata-Regular.ttf
        - asset: assets/fonts/Inconsolata/Inconsolata-Light.ttf
        - asset: assets/fonts/Inconsolata/Inconsolata-Medium.ttf
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-BoldItalic.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLight.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLightItalic.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Italic.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-LightItalic.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-MediumItalic.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBoldItalic.ttf

flutter_native_splash:
  color: "#000000"
