import 'dart:async';
import 'dart:developer' as developer;

class UpdateNotifications {
  UpdateNotifications();

  final _controller = StreamController<Set<String>>.broadcast();
  final _localController = StreamController<Set<String>>.broadcast();
  final _affectedIds = <String>{};
  final _affectedIdsFromSync = <String>{};
  final _uiOnlyIds = <String>{};
  Timer? _timer;
  Timer? _fromSyncTimer;
  Timer? _uiOnlyTimer;
  bool _isDisposed = false;

  /// Stream of all update notifications (both local and sync-originated).
  ///
  /// Used by UI widgets and other consumers that need to react to all changes.
  Stream<Set<String>> get updateStream => _controller.stream;

  /// Stream of only locally-originated update notifications.
  ///
  /// Used by agent wake orchestration so that sync-originated changes do not
  /// trigger agent wakes — the source device already ran the agent.
  Stream<Set<String>> get localUpdateStream => _localController.stream;

  // TODO(debug): remove after wake-loop investigation.
  // Entity IDs to trace — any local notify() containing one of these
  // will log the caller's stack trace.
  final debugEntityIds = <String>{};

  void notify(Set<String> affectedIds, {bool fromSync = false}) {
    if (_isDisposed) return;

    if (!fromSync && debugEntityIds.isNotEmpty) {
      final hit = affectedIds.intersection(debugEntityIds);
      if (hit.isNotEmpty) {
        developer.log(
          'notify(local) hit=$hit — caller:\n${StackTrace.current}',
          name: 'UpdateNotifications.DEBUG',
        );
      }
    }

    if (fromSync) {
      _affectedIdsFromSync.addAll(affectedIds);
      _fromSyncTimer ??= Timer(const Duration(seconds: 1), () {
        if (_affectedIdsFromSync.isNotEmpty) {
          _controller.add({..._affectedIdsFromSync});
          _affectedIdsFromSync.clear();
        }
        _fromSyncTimer = null;
      });
    } else {
      _affectedIds.addAll(affectedIds);

      _timer ??= Timer(const Duration(milliseconds: 100), () {
        if (_affectedIds.isNotEmpty) {
          final batch = {..._affectedIds};
          _controller.add(batch);
          _localController.add(batch);
          _affectedIds.clear();
        }
        _timer = null;
      });
    }
  }

  /// Notify UI providers without triggering agent wake orchestration.
  ///
  /// Broadcasts only to [updateStream], bypassing [localUpdateStream].
  /// Use this for notifications generated by the agent system itself (e.g.
  /// wake-completion) that must refresh UI state but must not feed back into
  /// the wake orchestrator.
  void notifyUiOnly(Set<String> affectedIds) {
    if (_isDisposed) return;
    _uiOnlyIds.addAll(affectedIds);
    _uiOnlyTimer ??= Timer(const Duration(milliseconds: 100), () {
      if (_uiOnlyIds.isNotEmpty) {
        _controller.add({..._uiOnlyIds});
        _uiOnlyIds.clear();
      }
      _uiOnlyTimer = null;
    });
  }

  Future<void> dispose() async {
    if (_isDisposed) return;
    _isDisposed = true;
    _timer?.cancel();
    _timer = null;
    _fromSyncTimer?.cancel();
    _fromSyncTimer = null;
    _uiOnlyTimer?.cancel();
    _uiOnlyTimer = null;
    _affectedIds.clear();
    _affectedIdsFromSync.clear();
    _uiOnlyIds.clear();
    await _controller.close();
    await _localController.close();
  }
}

const habitCompletionNotification = 'HABIT_COMPLETION';
const textEntryNotification = 'TEXT_ENTRY';
const taskNotification = 'TASK';
const surveyNotification = 'SURVEY';
const eventNotification = 'EVENT';
const audioNotification = 'AUDIO';
const imageNotification = 'IMAGE';
const workoutNotification = 'WORKOUT';
const aiResponseNotification = 'AI_RESPONSE';
const dayPlanNotification = 'DAY_PLAN';
const ratingNotification = 'RATING';
const projectNotification = 'PROJECT';
const categoriesNotification = 'CATEGORIES_CHANGED';
const habitsNotification = 'HABITS_CHANGED';
const dashboardsNotification = 'DASHBOARDS_CHANGED';
const measurablesNotification = 'MEASURABLES_CHANGED';
const labelsNotification = 'LABELS_CHANGED';
const settingsNotification = 'SETTINGS_CHANGED';
const privateToggleNotification = 'PRIVATE_FLAG_TOGGLED';
const labelUsageNotification = 'LABEL_USAGE_CHANGED';
const agentNotification = 'AGENT_CHANGED';

/// Zone key set to `true` during agent wake execution.
///
/// Code running inside this zone (e.g. tool handlers writing to the
/// journal DB) should route notifications through `notifyUiOnly` instead
/// of `notify` to prevent the wake orchestrator from re-triggering the
/// agent on its own writes.
const agentExecutionZoneKey = #agentExecution;

/// Returns `true` when the current code is executing inside an agent
/// wake cycle.
bool get isAgentExecution => Zone.current[agentExecutionZoneKey] == true;

const projectEntityUpdatePrefix = 'PROJECT_ENTITY_UPDATE:';

String projectEntityUpdateNotification(String projectId) {
  return '$projectEntityUpdatePrefix$projectId';
}
