# Pre-commit hooks for code quality
repos:
  # Black - Code formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: Format Python code with Black
        language_version: python3
        args: [--line-length=120]

  # Flake8 - Linting and security
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: Lint Python code with Flake8
        args: [--config=services/gemma-local/.flake8]  # Use the project's flake8 config
        additional_dependencies:
          - bandit[toml]  # Security linting
          - flake8-bugbear  # Additional bug detection
          - flake8-comprehensions  # Better comprehensions
          - flake8-simplify  # Code simplification suggestions

  # MyPy - Type checking (only on src/ directory)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: Type check with MyPy
        files: ^src/.*\.py$
        args: [--config-file=mypy.ini]
        additional_dependencies:
          - types-setuptools

  # Built-in hooks for basic checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Ensure files end with newline
      - id: check-yaml
        name: Validate YAML files
      - id: check-json
        name: Validate JSON files
      - id: check-toml
        name: Validate TOML files
      - id: check-merge-conflict
        name: Check for merge conflict markers
      - id: debug-statements
        name: Check for debug statements
        language_version: python3

  # Security scanning with Bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: Security check with Bandit
        args: [--format, json, --severity-level, medium]
        files: \.py$

# Global settings
default_language_version:
  python: python3.13

# Performance: fail fast on first error
fail_fast: true

# CI settings
ci:
  autofix_commit_msg: 'style: auto-fix pre-commit hooks'
  autoupdate_commit_msg: 'ci: pre-commit autoupdate'
