name: wisely
description: A Smart Journal.
publish_to: 'none'
version: 0.1.84+114

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_health_fit:
    git: https://github.com/metaflowltd/flutter_health_fit.git

  research_package:
    git: https://github.com/matthiasn/research.package.git

  audio_video_progress_bar: ^0.10.0
  bloc: ^8.0.1
  bloc_test: ^9.0.1
  cached_network_image: ^3.1.0
  connectivity_plus: ^2.0.2
  crypto: ^3.0.1
  cryptography: ^2.0.2
  cupertino_icons: ^1.0.2
  dart_geohash: ^2.0.1
  delta_markdown: ^0.3.0
  device_info_plus: ^3.1.0
  enough_mail: ^1.3.6
  equatable: ^2.0.3
  exif: ^3.0.1
  flutter_bloc: ^8.0.0
  flutter_dotenv: ^5.0.2
  flutter_fgbg: ^0.1.0
  flutter_form_builder: ^6.1.0+1
  flutter_image_compress: ^1.1.0
  flutter_map: ^0.14.0
  flutter_native_timezone: ^2.0.0
  flutter_quill: ^2.0.9
  flutter_secure_storage: ^5.0.0
  flutter_sound: ^8.3.12
  freezed_annotation: ^1.0.0
  health: 3.2.1
  hydrated_bloc: 8.0.0-dev.4
  intl: ^0.17.0
  json_annotation: ^4.3.0
  just_audio: ^0.9.12
  keyboard_dismisser: ^2.0.0
  latlong2: ^0.8.1
  location: ^4.3.0
  material_design_icons_flutter: ^5.0.6295
  mocktail: ^0.2.0
  mutex: ^3.0.0
  package_info_plus: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.5
  permission_handler: ^8.1.6
  qr_code_scanner: ^0.6.1
  qr_flutter: ^4.0.0
  # research_package: ^0.6.7
  sentry_flutter: ^6.0.1
  sqflite: ^2.0.0+4
  syncfusion_flutter_datepicker: ^19.3.46
  tinycolor2: ^2.0.0
  uuid: ^3.0.4
  wechat_assets_picker: ^6.2.2
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  dart_code_metrics: ^4.6.0
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.1
  freezed: ^1.0.0
  glados: ^1.0.2
  json_serializable: ^6.0.0
  sentry_dart_plugin: ^1.0.0-beta.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/sqlite/
    # from https://www.iconfinder.com/paomedia
    - assets/images/map/299087_marker_map_icon.png
    # from https://www.iconfinder.com/recepkutuk
    - assets/images/map/728975_location_map_marker_pin_place_icon.png

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-ExtraLight.ttf
        - asset: assets/fonts/Oswald-Light.ttf
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Medium.ttf
        - asset: assets/fonts/Oswald-SemiBold.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
    - family: ShareTechMono
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf

flutter_native_splash:
  color: "#444455"