name: wisely
description: A Smart Journal.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.11+12

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  location: ^4.3.0
  flutter_quill: ^2.0.5
  uuid: ^3.0.4
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.5.2
  flutter_map: ^0.14.0
  latlong2: ^0.8.1
  cached_network_image: ^3.1.0
  flutter_secure_storage: ^5.0.0-beta.1
  enough_mail: ^1.3.6
  yaml: ^3.1.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  health: ^3.1.1+1
  image_picker: ^0.8.4+2
  delta_markdown: ^0.3.0
  flutter_sound: ^8.3.12
  path_provider: ^2.0.5
  just_audio: ^0.9.12
  audio_video_progress_bar: ^0.9.0
  bloc: ^8.0.0-dev.3
  bloc_test: ^9.0.0-dev.3
  flutter_bloc: ^8.0.0-dev.2
  hydrated_bloc: ^8.0.0-dev.2
  mocktail: ^0.2.0
  equatable: ^2.0.3
  intl: ^0.17.0
  tinycolor2: ^2.0.0
  json_annotation: ^4.1.0
  flutter_native_timezone: ^2.0.0
  cryptography: ^2.0.2
  encrypt: ^5.0.1
  syncfusion_flutter_datepicker: ^19.3.45

dev_dependencies:
  flutter_test:
    sdk: flutter
  glados: ^1.0.2
  json_serializable: ^6.0.0
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sqlite/create_db.sql
    - assets/config/mail.yaml
    # from https://www.iconfinder.com/paomedia
    - assets/images/map/299087_marker_map_icon.png
    # from https://www.iconfinder.com/recepkutuk
    - assets/images/map/728975_location_map_marker_pin_place_icon.png

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-ExtraLight.ttf
        - asset: assets/fonts/Oswald-Light.ttf
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Medium.ttf
        - asset: assets/fonts/Oswald-SemiBold.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
    - family: ShareTechMono
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf
