steps:
  - label: ":windows: :github: MISX 📦"
    key: "windows_build"
    commands:
      - "flutter clean"
      - "flutter pub get"
      - "flutter pub run build_runner build --delete-conflicting-outputs"
      - "flutter test"
      - "flutter build windows -v"
      - "flutter pub run msix:create"
    agents:
      os: "windows"
