steps:
  - group: "Codegen & Test"
    key: "codegen_test"
    steps:
      - label: "🧽 Clean "
        key: "apple_clean"
        commands:
          - "flutter clean"
        agents:
          os: "macOS"

      - label: "🛠 Dependencies "
        key: "apple_deps"
        depends_on:
          - "apple_clean"
        commands:
          - "flutter pub get"
          - "mkdir -p /tmp/buildkite/${BUILDKITE_COMMIT}/"
          - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "macOS"
        # Workaround for rsync warning about vanished files,
        # which is inconsequential here but returns exit code
        # 24 and is therefore interpreted as a failure
        soft_fail:
          - exit_status: 24

      - label: "🛠 Codegen "
        key: "apple_codegen"
        depends_on:
          - "apple_deps"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "flutter pub run build_runner build --delete-conflicting-outputs"
          - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "macOS"
        artifact_paths:
          - "missing_translations.txt"
        soft_fail:
          - exit_status: 24

      - label: "🔬 Test "
        key: "apple_test"
        depends_on:
          - "apple_codegen"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "flutter test"
        agents:
          os: "macOS"
        soft_fail:
          - exit_status: 24

  #################

  - label: "📱 iOS Build 📦"
    key: "ios_build"
    depends_on:
      - "codegen_test"
    commands:
      - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - "make ios_build_ipa"
      - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
    agents:
      os: "macOS"
    soft_fail:
      - exit_status: 24

  #################

  - group: "📱 iOS TestFlight"
    key: "ios_testflight"
    depends_on:
      - "ios_build"
    steps:
      - label: "📱👟 iOS fastlane build "
        key: "ios_fastlane_build"
        depends_on:
          - "ios_build"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "make ios_fastlane_build"
          - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "macOS"
        soft_fail:
          - exit_status: 24

      - label: "📱🚀 iOS fastlane TestFlight "
        key: "ios_fastlane_testflight"
        depends_on:
          - "ios_fastlane_build"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "make ios_fastlane_upload"
        agents:
          os: "macOS"
        soft_fail:
          - exit_status: 24

  #################

  - label: ":mac: Build 📦 "
    key: "macos_build"
    depends_on:
      - "codegen_test"
    commands:
      - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - "make macos_build_flutter"
      - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
    agents:
      os: "macOS"
    soft_fail:
      - exit_status: 24

  #################

  - group: ":mac: TestFlight"
    key: "macos_testflight"
    depends_on:
      - "macos_build"
    steps:
      - label: ":mac: 👟 fastlane build "
        key: "macos_fastlane_build"
        depends_on:
          - "macos_build"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "make macos_fastlane_build"
          - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "macOS"
        soft_fail:
          - exit_status: 24

      - label: ":mac: 🚀 fastlane TestFlight "
        key: "macos_fastlane_testflight"
        depends_on:
          - "macos_fastlane_build"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "make macos_fastlane_upload"
        agents:
          os: "macOS"
        soft_fail:
          - exit_status: 24

  #################

  - label: "Create :github: Release "
    key: "create_github_prerelease"
    command:
      - "gh release create -p --generate-notes --target ${BUILDKITE_COMMIT} ${BUILDKITE_BRANCH}"
    agents:
      os: "macOS"

  #################

  - group: ":mac: :github: Release"
    key: "macos_github_release"
    depends_on:
      - "macos_build"
    steps:
      - label: "🚀 macOS fastlane Export "
        key: "macos_fastlane_export"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "make macos_fastlane_export"
          - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        artifact_paths:
          - "build/export/Lotti.app"
        agents:
          os: "macOS"
        soft_fail:
          - exit_status: 24

      - label: ":mac: 💾 create DMG "
        key: "macos_dmg"
        depends_on:
          - "macos_fastlane_export"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "npx create-dmg build/export/Lotti.app build/export/"
          - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "macOS"
        soft_fail:
          - exit_status: 24

      - label: "⚖️ :mac: notarize DMG file "
        key: "macos_notarize"
        depends_on:
          - "macos_dmg"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "xcrun altool --notarize-app -f build/export/*.dmg --primary-bundle-id com.matthiasnehlsen.lotti -u $$APPLEID -p $$APPLEIDPASS"
        agents:
          os: "macOS"
        soft_fail:
          - exit_status: 24

      - label: ":mac: publish :github: Prerelease 🚀 "
        key: "macos_github_prerelease"
        depends_on:
          - "create_github_prerelease"
          - "macos_notarize"
        command:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "gh release upload ${BUILDKITE_BRANCH} build/export/*.dmg"
        agents:
          os: "macOS"
        soft_fail:
          - exit_status: 24

  #################

  - label: ":android: Bundle "
    key: "android_bundle"
    depends_on:
      - "codegen_test"
    command:
      - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - "flutter build appbundle"
      - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
    agents:
      os: "macOS"
    soft_fail:
      - exit_status: 24

  #################

  - group: ":android: :github: Release"
    key: "android_github_release"
    depends_on:
      - "android_bundle"
    steps:
      - label: ":android: Android create APKs "
        key: "android_apks"
        depends_on:
          - "android_bundle"
        command:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "bundletool build-apks --mode universal --bundle build/app/outputs/bundle/release/app-release.aab --output build/android/lotti.apks --overwrite"
          - "cp build/android/lotti.apks build/android/lotti.zip"
          - "cd build/android && unzip lotti.zip && cd -"
          - "rsync -ar --exclude 'build/ios' --exclude 'build/macos' ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "macOS"
        soft_fail:
          - exit_status: 24

      - label: ":android: 🚀 publish :github: Prerelease "
        key: "android_github_prerelease"
        depends_on:
          - "create_github_prerelease"
          - "android_apks"
        command:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "gh release upload ${BUILDKITE_BRANCH} build/android/universal.apk"
          - "gh release upload ${BUILDKITE_BRANCH} build/app/outputs/bundle/release/app-release.aab"
        agents:
          os: "macOS"
        soft_fail:
          - exit_status: 24
