steps:
  - group: "Codegen & Test"
    key: "codegen_test"
    steps:
      - label: "🛠 Dependencies & Codegen"
        key: "apple_deps"
        commands:
          - "flutter pub get"
          - "flutter gen-l10n"
          - "mkdir -p /tmp/buildkite/${BUILDKITE_COMMIT}/"
          - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "macOS"
        artifact_paths:
          - "missing_translations.txt"
        # Workaround for rsync warning about vanished files,
        # which is inconsequential here but returns exit code
        # 24 and is therefore interpreted as a failure
        retry:
          automatic:
            - exit_status: 24

      - label: "🔬 Test Coverage "
        key: "apple_test"
        depends_on:
          - "apple_deps"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "make junit_test"
          - "make junit_upload"
        agents:
          os: "macOS"
        retry:
          automatic:
            - exit_status: 24

  #################

  - label: ":mac: Fluttium 🔬 "
    key: "fluttium"
    depends_on:
      - "apple_deps"
    commands:
      - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - touch ~/Library/Containers/com.matthiasn.lotti.dev
      - trash ~/Library/Containers/com.matthiasn.lotti.dev
      - "make activate_fluttium"
      - "make fluttium"
      - "make fluttium_docs"
    agents:
      os: "macOS"
    retry:
      automatic:
        - exit_status: 24

  #################

  - label: "📱 iOS TestFlight"
    key: "ios_build"
    depends_on:
      - "codegen_test"
    commands:
      - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - "make ios_build_ipa"
      - "make ios_fastlane_build"
      - "make ios_fastlane_upload"
    agents:
      os: "macOS"
    retry:
      automatic:
        - exit_status: 24

  #################

  - label: ":mac: fastlane TestFlight 🚀"
    key: "macos_build"
    depends_on:
      - "codegen_test"
    commands:
      - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - "make macos_build_flutter"
      - "make macos_fastlane_build"
      - "make macos_fastlane_upload"
    agents:
      os: "macOS"
    retry:
      automatic:
        - exit_status: 24

  #################

  - label: "Create :github: Release "
    key: "create_github_prerelease"
    command:
      - "gh release create -p --generate-notes --target ${BUILDKITE_COMMIT} ${BUILDKITE_BRANCH} || true"
    agents:
      os: "macOS"

#  #################

  - label: ":android: Bundle & Release"
    key: "android_bundle_release"
    depends_on:
      - "codegen_test"
    command:
      - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - "flutter build appbundle"
      - "flutter build apk --split-per-abi"
      - "gh release upload ${BUILDKITE_BRANCH} build/app/outputs/bundle/release/app-release.aab"
      - "gh release upload ${BUILDKITE_BRANCH} build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk"
      - "gh release upload ${BUILDKITE_BRANCH} build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
      - "gh release upload ${BUILDKITE_BRANCH} build/app/outputs/flutter-apk/app-x86_64-release.apk"
    agents:
      os: "macOS"
    retry:
      automatic:
        - exit_status: 24
