# Workaround for rsync warning about vanished files,
# which is inconsequential here but returns exit code
# 24 and is therefore interpreted as a failure
soft_fail:
  - exit_status: 24

steps:
  - group: "Windows codegen & test"
    key: "windows_codegen_test"
    steps:
      - label: ":windows: 🛠 Clean "
        key: "windows_clean"
        commands:
          - "flutter clean"
        agents:
          os: "windows"

      - label: ":windows: 🛠 Dependencies "
        key: "windows_deps"
        depends_on:
          - "windows_clean"
        commands:
          - "flutter pub get"
          - "wsl mkdir -p /tmp/buildkite/${BUILDKITE_COMMIT}/"
          - "wsl rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "windows"

      - label: ":windows: 🛠 Codegen "
        key: "windows_build_runner"
        depends_on:
          - "windows_deps"
        commands:
          - "wsl rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "flutter pub run build_runner build --delete-conflicting-outputs"
          - "wsl rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "windows"

      - label: ":windows: 🔬 Test "
        key: "windows_test"
        depends_on:
          - "windows_build_runner"
        commands:
          - "wsl rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "flutter test"
        agents:
          os: "windows"

  #################

  - label: ":windows: 🛠 Build "
    key: "windows_build"
    depends_on:
      - "windows_codegen_test"
    commands:
      - "wsl rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - "flutter build windows -v"
      - "wsl rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
    agents:
      os: "windows"

  - label: ":github: MSIX 📦"
    key: "windows_msix"
    depends_on:
      - "windows_build"
    commands:
      - "wsl rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - "flutter pub run msix:create"
    agents:
      os: "windows"
