steps:
  - label: "📱 iOS Build 🏭 "
    key: "ios_build"
    command:
    - "make ios_build"
    - "mkdir -p /tmp/buildkite/$$BUILDKITE_COMMIT"
    - "rsync -ar build /tmp/buildkite/$$BUILDKITE_COMMIT/"
    artifact_paths:
      - "missing_translations.txt"

  - label: "📱 iOS fastlane build 👟 "
    key: "ios_fastlane_build"
    depends_on:
      - "ios_build"
    command:
    - "mkdir -p build"
    - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/build/ios build/"
    - "make ios_fastlane_build"
    - "rsync -ar ios /tmp/buildkite/$$BUILDKITE_COMMIT/"

  - label: "📱 iOS fastlane TestFlight upload 🚀 "
    key: "ios_fastlane_testflight"
    depends_on:
      - "ios_fastlane_build"
    command:
    - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ios/Runner.ipa ios/"
    - "make ios_fastlane_upload"

#  - label: "💻 macOS TestFlight 💻"
#    command:
#    - "make macos_build"
#    - "make macos_fastlane_build"
#    - "make macos_fastlane_upload"
#    artifact_paths:
#      - "build/macos/Build/Products/**/*"
