steps:
  - group: "Codegen & Test"
    key: "codegen_test"
    steps:
      - label: "🧽 Clean "
        key: "apple_clean"
        commands:
          - "flutter clean"
        agents:
          os: "macOS"

      - label: "🛠 Dependencies "
        key: "apple_deps"
        depends_on:
          - "apple_clean"
        commands:
          - "flutter pub get"
          - "mkdir -p /tmp/buildkite/${BUILDKITE_COMMIT}/"
          - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "macOS"
        # Workaround for rsync warning about vanished files,
        # which is inconsequential here but returns exit code
        # 24 and is therefore interpreted as a failure
        retry:
          automatic:
            - exit_status: 24

      - label: "🛠 Codegen "
        key: "apple_codegen"
        depends_on:
          - "apple_deps"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "flutter gen-l10n"
          - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "macOS"
        artifact_paths:
          - "missing_translations.txt"
        retry:
          automatic:
            - exit_status: 24

      - label: "🔬 Test Coverage "
        key: "apple_test"
        depends_on:
          - "apple_codegen"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "make junit_test"
          - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "macOS"
        retry:
          automatic:
            - exit_status: 24

      - label: "🔬 Test Report "
        key: "apple_test_report"
        depends_on:
          - "apple_test"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "make junit_upload"
        agents:
          os: "macOS"
        retry:
          automatic:
            - exit_status: 24

  #################

  - label: ":mac: Fluttium 🔬 "
    key: "fluttium"
    depends_on:
      - "apple_codegen"
    commands:
      - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - touch ~/Library/Containers/com.matthiasn.lotti.dev
      - trash ~/Library/Containers/com.matthiasn.lotti.dev
      - "make activate_fluttium"
      - "make fluttium"
      - "make fluttium_docs"
      - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
    agents:
      os: "macOS"
    retry:
      automatic:
        - exit_status: 24

  #################

  - label: "📱 iOS Build 📦"
    key: "ios_build"
    depends_on:
      - "codegen_test"
    commands:
      - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - "make ios_build_ipa"
      - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
    agents:
      os: "macOS"
    retry:
      automatic:
        - exit_status: 24

  #################

  - group: "📱 iOS TestFlight"
    key: "ios_testflight"
    depends_on:
      - "ios_build"
    steps:
      - label: "📱👟 iOS fastlane build "
        key: "ios_fastlane_build"
        depends_on:
          - "ios_build"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "make ios_fastlane_build"
          - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "macOS"
        retry:
          automatic:
            - exit_status: 24

      - label: "📱🚀 iOS fastlane TestFlight "
        key: "ios_fastlane_testflight"
        depends_on:
          - "ios_fastlane_build"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "make ios_fastlane_upload"
        agents:
          os: "macOS"
        retry:
          automatic:
            - exit_status: 24

  #################

  - label: ":mac: Build 📦 "
    key: "macos_build"
    depends_on:
      - "codegen_test"
    commands:
      - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - "make macos_build_flutter"
      - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
    agents:
      os: "macOS"
    retry:
      automatic:
        - exit_status: 24

  #################

  - group: ":mac: TestFlight"
    key: "macos_testflight"
    depends_on:
      - "macos_build"
    steps:
      - label: ":mac: 👟 fastlane build "
        key: "macos_fastlane_build"
        depends_on:
          - "macos_build"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "make macos_fastlane_build"
          - "rsync -ar ./ /tmp/buildkite/${BUILDKITE_COMMIT}/"
        agents:
          os: "macOS"
        retry:
          automatic:
            - exit_status: 24

      - label: ":mac: 🚀 fastlane TestFlight "
        key: "macos_fastlane_testflight"
        depends_on:
          - "macos_fastlane_build"
        commands:
          - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
          - "make macos_fastlane_upload"
        agents:
          os: "macOS"
        retry:
          automatic:
            - exit_status: 24

  #################

  - label: "Create :github: Release "
    key: "create_github_prerelease"
    command:
      - "gh release create -p --generate-notes --target ${BUILDKITE_COMMIT} ${BUILDKITE_BRANCH} || true"
    agents:
      os: "macOS"

#  #################

  - label: ":android: Bundle & Release"
    key: "android_bundle_release"
    depends_on:
      - "codegen_test"
    command:
      - "rsync -ar /tmp/buildkite/${BUILDKITE_COMMIT}/ ./"
      - "flutter build appbundle"
      - "flutter build apk --split-per-abi"
      - "gh release upload ${BUILDKITE_BRANCH} build/app/outputs/bundle/release/app-release.aab"
      - "gh release upload ${BUILDKITE_BRANCH} build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk"
      - "gh release upload ${BUILDKITE_BRANCH} build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
      - "gh release upload ${BUILDKITE_BRANCH} build/app/outputs/flutter-apk/app-x86_64-release.apk"
    agents:
      os: "macOS"
    retry:
      automatic:
        - exit_status: 24
