import 'dart:convert';
import 'dart:io';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:path/path.dart' as path;

const _outputRelativePath = 'test/.test_optimizer.dart';
const testTargetsRelativePath = 'test/.test_targets.json';

/// Generates the stable optimized test entrypoint used by sharded CI.
Future<File> generateTestOptimizer({required String packageRoot}) async {
  final testDirectory = Directory(path.join(packageRoot, 'test'));
  if (!testDirectory.existsSync()) {
    throw FileSystemException(
      'Test directory does not exist',
      testDirectory.path,
    );
  }

  final testPaths = <String>[];
  final standalonePaths = <String>[];
  for (final entity in testDirectory.listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('_test.dart')) continue;
    final contents = await entity.readAsString();
    // Library metadata belongs to a suite, not the imported main() function.
    // Keep annotated suites intact so the test runner interprets their tags,
    // timeouts, platform selectors, skips and retries without losing context.
    final unit = parseString(content: contents).unit;
    if (unit.directives.whereType<LibraryDirective>().any(
      (directive) => directive.metadata.isNotEmpty,
    )) {
      standalonePaths.add(
        path.relative(entity.path, from: packageRoot).replaceAll(r'\', '/'),
      );
      continue;
    }
    testPaths.add(
      path
          .relative(entity.path, from: testDirectory.path)
          .replaceAll(r'\', '/'),
    );
  }
  testPaths.sort();
  standalonePaths.sort();

  final output = File(path.join(packageRoot, _outputRelativePath));
  await output.writeAsString(_renderBundle(testPaths));
  await File(path.join(packageRoot, testTargetsRelativePath)).writeAsString(
    jsonEncode([_outputRelativePath, ...standalonePaths]),
  );
  return output;
}

String _renderBundle(List<String> testPaths) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
    ..writeln('// Generated by tool/ci/generate_test_optimizer.dart.')
    ..writeln()
    ..writeln("import 'dart:io';")
    ..writeln("import 'dart:typed_data';")
    ..writeln()
    ..writeln("import 'package:flutter_test/flutter_test.dart';")
    ..writeln();

  for (var index = 0; index < testPaths.length; index++) {
    buffer.writeln("import '${testPaths[index]}' as _test$index;");
  }

  buffer
    ..writeln()
    ..writeln('void main() {')
    ..write(
      '  goldenFileComparator = _TestOptimizationAwareGoldenFileComparator(',
    )
    ..writeln('goldenFileComparator as LocalFileComparator);');
  for (var index = 0; index < testPaths.length; index++) {
    buffer.writeln(
      "  group('${testPaths[index]}', () { _test$index.main(); });",
    );
  }
  buffer
    ..writeln('}')
    ..writeln()
    ..writeln(
      'class _TestOptimizationAwareGoldenFileComparator '
      'extends GoldenFileComparator {',
    )
    ..write('  _TestOptimizationAwareGoldenFileComparator(')
    ..writeln(
      'this.previousGoldenFileComparator) : goldenFilePaths = '
      '_goldenFilePaths;',
    )
    ..writeln()
    ..writeln('  final List<String> goldenFilePaths;')
    ..writeln(
      '  final LocalFileComparator previousGoldenFileComparator;',
    )
    ..writeln()
    ..writeln(
      '  static List<String> get _goldenFilePaths => Directory.fromUri(',
    )
    ..writeln('    (goldenFileComparator as LocalFileComparator).basedir,')
    ..writeln('  )')
    ..writeln('      .listSync(recursive: true, followLinks: true)')
    ..writeln('      .whereType<File>()')
    ..writeln('      .map((file) => file.path)')
    ..writeln("      .where((filePath) => filePath.endsWith('.png'))")
    ..writeln('      .toList();')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Future<bool> compare(Uint8List imageBytes, Uri golden) =>')
    ..writeln(
      '      previousGoldenFileComparator.compare(imageBytes, golden);',
    )
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Uri getTestUri(Uri key, int? version) {')
    ..writeln('    final keyString = key.toFilePath();')
    ..writeln('    return Uri.parse(')
    ..writeln('      goldenFilePaths.singleWhere(')
    ..writeln('        (goldenPath) => goldenPath.endsWith(keyString),')
    ..writeln('      ),')
    ..writeln('    );')
    ..writeln('  }')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Future<void> update(Uri golden, Uint8List imageBytes) =>')
    ..writeln(
      '      previousGoldenFileComparator.update(golden, imageBytes);',
    )
    ..writeln('}');
  return buffer.toString();
}

Future<void> main() async {
  await generateTestOptimizer(packageRoot: Directory.current.path);
}
