import 'dart:convert';
import 'dart:io';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:path/path.dart' as path;

const _outputRelativePath = 'test/.test_optimizer.dart';
const testTargetsRelativePath = 'test/.test_targets.json';

/// Generates a stable bundle containing only the selected shard’s test files.
Future<File> generateTestOptimizer({
  required String packageRoot,
  Set<String> excludedSuiteTags = const {},
  int totalShards = 1,
  int shardIndex = 0,
}) async {
  if (totalShards < 1 || shardIndex < 0 || shardIndex >= totalShards) {
    throw ArgumentError('Invalid shard $shardIndex of $totalShards');
  }
  final testDirectory = Directory(path.join(packageRoot, 'test'));
  if (!testDirectory.existsSync()) {
    throw FileSystemException(
      'Test directory does not exist',
      testDirectory.path,
    );
  }

  final testPaths = <String>[];
  final standalonePaths = <String>[];
  final sizes = <String, int>{};
  for (final entity in testDirectory.listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('_test.dart')) continue;
    final contents = await entity.readAsString();
    // Library metadata belongs to a suite, not the imported main() function.
    // Keep annotated suites intact so the test runner interprets their tags,
    // timeouts, platform selectors, skips and retries without losing context.
    final libraries = parseString(
      content: contents,
    ).unit.directives.whereType<LibraryDirective>();
    if (libraries.any(
      (directive) => _isExcluded(directive, excludedSuiteTags),
    )) {
      continue;
    }
    final relative = path
        .relative(entity.path, from: packageRoot)
        .replaceAll(r'\', '/');
    sizes[relative] = contents.length;
    if (libraries.any((directive) => directive.metadata.isNotEmpty)) {
      standalonePaths.add(relative);
      continue;
    }
    testPaths.add(
      path
          .relative(entity.path, from: testDirectory.path)
          .replaceAll(r'\', '/'),
    );
  }
  // Greedily balance source size before compilation. Path tie-breaks keep the
  // assignment reproducible without a timing artifact or machine-local state.
  final candidates = sizes.keys.toList()
    ..sort((a, b) {
      final bySize = sizes[b]!.compareTo(sizes[a]!);
      return bySize == 0 ? a.compareTo(b) : bySize;
    });
  final loads = List<int>.filled(totalShards, 0);
  final selected = <String>{};
  for (final candidate in candidates) {
    var shard = 0;
    for (var index = 1; index < totalShards; index++) {
      if (loads[index] < loads[shard]) shard = index;
    }
    loads[shard] += sizes[candidate]!;
    if (shard == shardIndex) selected.add(candidate);
  }
  testPaths.removeWhere((file) => !selected.contains('test/$file'));
  standalonePaths.removeWhere((file) => !selected.contains(file));
  testPaths.sort();
  standalonePaths.sort();

  final output = File(path.join(packageRoot, _outputRelativePath));
  await output.writeAsString(_renderBundle(testPaths));
  await File(path.join(packageRoot, testTargetsRelativePath)).writeAsString(
    jsonEncode([_outputRelativePath, ...standalonePaths]),
  );
  return output;
}

// Only inherited literal tags can prove that every test is excluded. Unknown
// constants and per-test tags stay with Flutter's own discovery/filtering.
bool _isExcluded(LibraryDirective library, Set<String> excludedTags) {
  for (final annotation in library.metadata) {
    if (annotation.name.name.split('.').last != 'Tags') continue;
    final arguments = annotation.arguments?.arguments;
    if (arguments == null || arguments.length != 1) continue;
    final elements = switch (arguments.single) {
      ListLiteral(:final elements) => elements,
      SetOrMapLiteral(:final elements) => elements,
      _ => const <CollectionElement>[],
    };
    if (elements.whereType<StringLiteral>().any(
      (tag) => excludedTags.contains(tag.stringValue),
    )) {
      return true;
    }
  }
  return false;
}

String _renderBundle(List<String> testPaths) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
    ..writeln('// Generated by tool/ci/generate_test_optimizer.dart.')
    ..writeln()
    ..writeln("import 'dart:io';")
    ..writeln("import 'dart:typed_data';")
    ..writeln()
    ..writeln("import 'package:flutter_test/flutter_test.dart';")
    ..writeln();

  for (var index = 0; index < testPaths.length; index++) {
    buffer.writeln("import '${testPaths[index]}' as _test$index;");
  }

  buffer
    ..writeln()
    ..writeln('void main() {')
    ..write(
      '  goldenFileComparator = _TestOptimizationAwareGoldenFileComparator(',
    )
    ..writeln('goldenFileComparator as LocalFileComparator);');
  for (var index = 0; index < testPaths.length; index++) {
    buffer.writeln(
      "  group('${testPaths[index]}', () { _test$index.main(); });",
    );
  }
  buffer
    ..writeln('}')
    ..writeln()
    ..writeln(
      'class _TestOptimizationAwareGoldenFileComparator '
      'extends GoldenFileComparator {',
    )
    ..write('  _TestOptimizationAwareGoldenFileComparator(')
    ..writeln(
      'this.previousGoldenFileComparator) : goldenFilePaths = '
      '_goldenFilePaths;',
    )
    ..writeln()
    ..writeln('  final List<String> goldenFilePaths;')
    ..writeln(
      '  final LocalFileComparator previousGoldenFileComparator;',
    )
    ..writeln()
    ..writeln(
      '  static List<String> get _goldenFilePaths => Directory.fromUri(',
    )
    ..writeln('    (goldenFileComparator as LocalFileComparator).basedir,')
    ..writeln('  )')
    ..writeln('      .listSync(recursive: true, followLinks: true)')
    ..writeln('      .whereType<File>()')
    ..writeln('      .map((file) => file.path)')
    ..writeln("      .where((filePath) => filePath.endsWith('.png'))")
    ..writeln('      .toList();')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Future<bool> compare(Uint8List imageBytes, Uri golden) =>')
    ..writeln(
      '      previousGoldenFileComparator.compare(imageBytes, golden);',
    )
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Uri getTestUri(Uri key, int? version) {')
    ..writeln('    final keyString = key.toFilePath();')
    ..writeln('    return Uri.parse(')
    ..writeln('      goldenFilePaths.singleWhere(')
    ..writeln('        (goldenPath) => goldenPath.endsWith(keyString),')
    ..writeln('      ),')
    ..writeln('    );')
    ..writeln('  }')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Future<void> update(Uri golden, Uint8List imageBytes) =>')
    ..writeln(
      '      previousGoldenFileComparator.update(golden, imageBytes);',
    )
    ..writeln('}');
  return buffer.toString();
}

Future<void> main() async {
  await generateTestOptimizer(packageRoot: Directory.current.path);
}
