// Mocks generated by Mockito 5.4.5 from annotations
// in lotti/test/services/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:drift/drift.dart' as _i2;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:lotti/classes/entity_definitions.dart' as _i9;
import 'package:lotti/classes/entry_link.dart' as _i11;
import 'package:lotti/classes/journal_entities.dart' as _i8;
import 'package:lotti/classes/tag_type_definitions.dart' as _i10;
import 'package:lotti/database/database.dart' as _i3;
import 'package:lotti/database/logging_db.dart' as _i16;
import 'package:lotti/database/sync_db.dart' as _i13;
import 'package:lotti/features/sync/model/sync_message.dart' as _i14;
import 'package:lotti/features/sync/outbox/outbox_service.dart' as _i12;
import 'package:lotti/features/sync/vector_clock.dart' as _i7;
import 'package:lotti/services/logging_service.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeJournal_1 extends _i1.SmartFake implements _i3.Journal {
  _FakeJournal_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeIndex_2 extends _i1.SmartFake implements _i2.Index {
  _FakeIndex_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeConflicts_3 extends _i1.SmartFake implements _i3.Conflicts {
  _FakeConflicts_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeMeasurableTypes_4 extends _i1.SmartFake
    implements _i3.MeasurableTypes {
  _FakeMeasurableTypes_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeHabitDefinitions_5 extends _i1.SmartFake
    implements _i3.HabitDefinitions {
  _FakeHabitDefinitions_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeCategoryDefinitions_6 extends _i1.SmartFake
    implements _i3.CategoryDefinitions {
  _FakeCategoryDefinitions_6(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDashboardDefinitions_7 extends _i1.SmartFake
    implements _i3.DashboardDefinitions {
  _FakeDashboardDefinitions_7(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeConfigFlags_8 extends _i1.SmartFake implements _i3.ConfigFlags {
  _FakeConfigFlags_8(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTagEntities_9 extends _i1.SmartFake implements _i3.TagEntities {
  _FakeTagEntities_9(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTagged_10 extends _i1.SmartFake implements _i3.Tagged {
  _FakeTagged_10(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeLinkedEntries_11 extends _i1.SmartFake implements _i3.LinkedEntries {
  _FakeLinkedEntries_11(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _Fake$JournalDbManager_12 extends _i1.SmartFake
    implements _i3.$JournalDbManager {
  _Fake$JournalDbManager_12(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_13 extends _i1.SmartFake
    implements _i2.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_13(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_14 extends _i1.SmartFake
    implements _i2.GeneratedDatabase {
  _FakeGeneratedDatabase_14(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_15 extends _i1.SmartFake
    implements _i2.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_15(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_16 extends _i1.SmartFake
    implements _i2.DatabaseConnection {
  _FakeDatabaseConnection_16(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeQueryExecutor_17 extends _i1.SmartFake implements _i2.QueryExecutor {
  _FakeQueryExecutor_17(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_18 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_18(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_19 extends _i1.SmartFake
    implements _i2.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_19(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeSelectable_20<T> extends _i1.SmartFake implements _i2.Selectable<T> {
  _FakeSelectable_20(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeMigrator_21 extends _i1.SmartFake implements _i2.Migrator {
  _FakeMigrator_21(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeFuture_22<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_22(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeInsertStatement_23<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.InsertStatement<T1, D1> {
  _FakeInsertStatement_23(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeUpdateStatement_24<T extends _i2.Table, D> extends _i1.SmartFake
    implements _i2.UpdateStatement<T, D> {
  _FakeUpdateStatement_24(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_25<T1 extends _i2.HasResultSet, D>
    extends _i1.SmartFake implements _i2.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_25(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_26<FirstT extends _i2.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i2.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_26(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_27<Row> extends _i1.SmartFake
    implements _i2.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_27(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDeleteStatement_28<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_28(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGenerationContext_29 extends _i1.SmartFake
    implements _i2.GenerationContext {
  _FakeGenerationContext_29(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [JournalDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalDb extends _i1.Mock implements _i3.JournalDb {
  MockJournalDb() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get inMemoryDatabase => (super.noSuchMethod(
        Invocation.getter(#inMemoryDatabase),
        returnValue: false,
      ) as bool);

  @override
  set inMemoryDatabase(bool? _inMemoryDatabase) => super.noSuchMethod(
        Invocation.setter(#inMemoryDatabase, _inMemoryDatabase),
        returnValueForMissingStub: null,
      );

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i2.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_0(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i2.MigrationStrategy);

  @override
  _i3.Journal get journal => (super.noSuchMethod(
        Invocation.getter(#journal),
        returnValue: _FakeJournal_1(this, Invocation.getter(#journal)),
      ) as _i3.Journal);

  @override
  _i2.Index get idxJournalDateFromAsc => (super.noSuchMethod(
        Invocation.getter(#idxJournalDateFromAsc),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxJournalDateFromAsc),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxJournalDateFromDesc => (super.noSuchMethod(
        Invocation.getter(#idxJournalDateFromDesc),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxJournalDateFromDesc),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxJournalDateToAsc => (super.noSuchMethod(
        Invocation.getter(#idxJournalDateToAsc),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxJournalDateToAsc),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxJournalDateToDesc => (super.noSuchMethod(
        Invocation.getter(#idxJournalDateToDesc),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxJournalDateToDesc),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxJournalTab => (super.noSuchMethod(
        Invocation.getter(#idxJournalTab),
        returnValue: _FakeIndex_2(this, Invocation.getter(#idxJournalTab)),
      ) as _i2.Index);

  @override
  _i2.Index get idxJournalTasks => (super.noSuchMethod(
        Invocation.getter(#idxJournalTasks),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxJournalTasks),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxJournalTypeSubtype => (super.noSuchMethod(
        Invocation.getter(#idxJournalTypeSubtype),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxJournalTypeSubtype),
        ),
      ) as _i2.Index);

  @override
  _i3.Conflicts get conflicts => (super.noSuchMethod(
        Invocation.getter(#conflicts),
        returnValue: _FakeConflicts_3(this, Invocation.getter(#conflicts)),
      ) as _i3.Conflicts);

  @override
  _i3.MeasurableTypes get measurableTypes => (super.noSuchMethod(
        Invocation.getter(#measurableTypes),
        returnValue: _FakeMeasurableTypes_4(
          this,
          Invocation.getter(#measurableTypes),
        ),
      ) as _i3.MeasurableTypes);

  @override
  _i3.HabitDefinitions get habitDefinitions => (super.noSuchMethod(
        Invocation.getter(#habitDefinitions),
        returnValue: _FakeHabitDefinitions_5(
          this,
          Invocation.getter(#habitDefinitions),
        ),
      ) as _i3.HabitDefinitions);

  @override
  _i2.Index get idxHabitDefinitionsId => (super.noSuchMethod(
        Invocation.getter(#idxHabitDefinitionsId),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxHabitDefinitionsId),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxHabitDefinitionsName => (super.noSuchMethod(
        Invocation.getter(#idxHabitDefinitionsName),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxHabitDefinitionsName),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxHabitDefinitionsPrivate => (super.noSuchMethod(
        Invocation.getter(#idxHabitDefinitionsPrivate),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxHabitDefinitionsPrivate),
        ),
      ) as _i2.Index);

  @override
  _i3.CategoryDefinitions get categoryDefinitions => (super.noSuchMethod(
        Invocation.getter(#categoryDefinitions),
        returnValue: _FakeCategoryDefinitions_6(
          this,
          Invocation.getter(#categoryDefinitions),
        ),
      ) as _i3.CategoryDefinitions);

  @override
  _i2.Index get idxCategoryDefinitionsId => (super.noSuchMethod(
        Invocation.getter(#idxCategoryDefinitionsId),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxCategoryDefinitionsId),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxCategoryDefinitionsName => (super.noSuchMethod(
        Invocation.getter(#idxCategoryDefinitionsName),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxCategoryDefinitionsName),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxCategoryDefinitionsPrivate => (super.noSuchMethod(
        Invocation.getter(#idxCategoryDefinitionsPrivate),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxCategoryDefinitionsPrivate),
        ),
      ) as _i2.Index);

  @override
  _i3.DashboardDefinitions get dashboardDefinitions => (super.noSuchMethod(
        Invocation.getter(#dashboardDefinitions),
        returnValue: _FakeDashboardDefinitions_7(
          this,
          Invocation.getter(#dashboardDefinitions),
        ),
      ) as _i3.DashboardDefinitions);

  @override
  _i2.Index get idxDashboardDefinitionsId => (super.noSuchMethod(
        Invocation.getter(#idxDashboardDefinitionsId),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxDashboardDefinitionsId),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxDashboardDefinitionsName => (super.noSuchMethod(
        Invocation.getter(#idxDashboardDefinitionsName),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxDashboardDefinitionsName),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxDashboardDefinitionsPrivate => (super.noSuchMethod(
        Invocation.getter(#idxDashboardDefinitionsPrivate),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxDashboardDefinitionsPrivate),
        ),
      ) as _i2.Index);

  @override
  _i3.ConfigFlags get configFlags => (super.noSuchMethod(
        Invocation.getter(#configFlags),
        returnValue: _FakeConfigFlags_8(
          this,
          Invocation.getter(#configFlags),
        ),
      ) as _i3.ConfigFlags);

  @override
  _i3.TagEntities get tagEntities => (super.noSuchMethod(
        Invocation.getter(#tagEntities),
        returnValue: _FakeTagEntities_9(
          this,
          Invocation.getter(#tagEntities),
        ),
      ) as _i3.TagEntities);

  @override
  _i2.Index get idxTagEntitiesId => (super.noSuchMethod(
        Invocation.getter(#idxTagEntitiesId),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxTagEntitiesId),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxTagEntitiesTag => (super.noSuchMethod(
        Invocation.getter(#idxTagEntitiesTag),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxTagEntitiesTag),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxTagEntitiesType => (super.noSuchMethod(
        Invocation.getter(#idxTagEntitiesType),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxTagEntitiesType),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxTagEntitiesPrivate => (super.noSuchMethod(
        Invocation.getter(#idxTagEntitiesPrivate),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxTagEntitiesPrivate),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxTagEntitiesInactive => (super.noSuchMethod(
        Invocation.getter(#idxTagEntitiesInactive),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxTagEntitiesInactive),
        ),
      ) as _i2.Index);

  @override
  _i3.Tagged get tagged => (super.noSuchMethod(
        Invocation.getter(#tagged),
        returnValue: _FakeTagged_10(this, Invocation.getter(#tagged)),
      ) as _i3.Tagged);

  @override
  _i2.Index get idxTaggedJournalId => (super.noSuchMethod(
        Invocation.getter(#idxTaggedJournalId),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxTaggedJournalId),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxTaggedTagEntityId => (super.noSuchMethod(
        Invocation.getter(#idxTaggedTagEntityId),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxTaggedTagEntityId),
        ),
      ) as _i2.Index);

  @override
  _i3.LinkedEntries get linkedEntries => (super.noSuchMethod(
        Invocation.getter(#linkedEntries),
        returnValue: _FakeLinkedEntries_11(
          this,
          Invocation.getter(#linkedEntries),
        ),
      ) as _i3.LinkedEntries);

  @override
  _i2.Index get idxLinkedEntriesFromId => (super.noSuchMethod(
        Invocation.getter(#idxLinkedEntriesFromId),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxLinkedEntriesFromId),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxLinkedEntriesToId => (super.noSuchMethod(
        Invocation.getter(#idxLinkedEntriesToId),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxLinkedEntriesToId),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxLinkedEntriesType => (super.noSuchMethod(
        Invocation.getter(#idxLinkedEntriesType),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxLinkedEntriesType),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxLinkedEntriesHidden => (super.noSuchMethod(
        Invocation.getter(#idxLinkedEntriesHidden),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxLinkedEntriesHidden),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxLinkedEntriesFromIdHidden => (super.noSuchMethod(
        Invocation.getter(#idxLinkedEntriesFromIdHidden),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxLinkedEntriesFromIdHidden),
        ),
      ) as _i2.Index);

  @override
  _i2.Index get idxLinkedEntriesToIdHidden => (super.noSuchMethod(
        Invocation.getter(#idxLinkedEntriesToIdHidden),
        returnValue: _FakeIndex_2(
          this,
          Invocation.getter(#idxLinkedEntriesToIdHidden),
        ),
      ) as _i2.Index);

  @override
  _i3.$JournalDbManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _Fake$JournalDbManager_12(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i3.$JournalDbManager);

  @override
  Iterable<_i2.TableInfo<_i2.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i2.TableInfo<_i2.Table, Object?>>[],
      ) as Iterable<_i2.TableInfo<_i2.Table, Object?>>);

  @override
  List<_i2.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i2.DatabaseSchemaEntity>[],
      ) as List<_i2.DatabaseSchemaEntity>);

  @override
  _i2.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_13(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i2.StreamQueryUpdateRules);

  @override
  _i2.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_14(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i2.GeneratedDatabase);

  @override
  _i2.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_15(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.DriftDatabaseOptions);

  @override
  _i2.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_16(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i2.DatabaseConnection);

  @override
  _i2.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i6.dummyValue<_i2.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i2.SqlTypes);

  @override
  _i2.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_17(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i2.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_18(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i4.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_19(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i2.DatabaseConnectionUser);

  @override
  _i5.Future<int> upsertJournalDbEntity(_i3.JournalDbEntity? entry) =>
      (super.noSuchMethod(
        Invocation.method(#upsertJournalDbEntity, [entry]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> addConflict(_i3.Conflict? conflict) => (super.noSuchMethod(
        Invocation.method(#addConflict, [conflict]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i7.VclockStatus> detectConflict(
    _i8.JournalEntity? existing,
    _i8.JournalEntity? updated,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#detectConflict, [existing, updated]),
        returnValue: _i5.Future<_i7.VclockStatus>.value(
          _i7.VclockStatus.equal,
        ),
      ) as _i5.Future<_i7.VclockStatus>);

  @override
  _i5.Future<void> insertTag(String? id, String? tagId) => (super.noSuchMethod(
        Invocation.method(#insertTag, [id, tagId]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addTagged(_i8.JournalEntity? journalEntity) =>
      (super.noSuchMethod(
        Invocation.method(#addTagged, [journalEntity]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> updateJournalEntity(
    _i8.JournalEntity? updated, {
    bool? overrideComparison = false,
    bool? overwrite = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJournalEntity,
          [updated],
          {#overrideComparison: overrideComparison, #overwrite: overwrite},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i3.JournalDbEntity?> entityById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#entityById, [id]),
        returnValue: _i5.Future<_i3.JournalDbEntity?>.value(),
      ) as _i5.Future<_i3.JournalDbEntity?>);

  @override
  _i5.Future<_i3.Conflict?> conflictById(String? id) => (super.noSuchMethod(
        Invocation.method(#conflictById, [id]),
        returnValue: _i5.Future<_i3.Conflict?>.value(),
      ) as _i5.Future<_i3.Conflict?>);

  @override
  _i5.Future<_i8.JournalEntity?> journalEntityById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#journalEntityById, [id]),
        returnValue: _i5.Future<_i8.JournalEntity?>.value(),
      ) as _i5.Future<_i8.JournalEntity?>);

  @override
  _i5.Stream<_i8.JournalEntity?> watchJournalEntityById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#watchJournalEntityById, [id]),
        returnValue: _i5.Stream<_i8.JournalEntity?>.empty(),
      ) as _i5.Stream<_i8.JournalEntity?>);

  @override
  _i5.Future<List<String>> entryIdsByTagId(String? tagId) =>
      (super.noSuchMethod(
        Invocation.method(#entryIdsByTagId, [tagId]),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<List<_i8.JournalEntity>> getJournalEntities({
    required List<String>? types,
    required List<bool>? starredStatuses,
    required List<bool>? privateStatuses,
    required List<int>? flaggedStatuses,
    required List<String>? ids,
    Set<String>? categoryIds,
    int? limit = 500,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getJournalEntities, [], {
          #types: types,
          #starredStatuses: starredStatuses,
          #privateStatuses: privateStatuses,
          #flaggedStatuses: flaggedStatuses,
          #ids: ids,
          #categoryIds: categoryIds,
          #limit: limit,
          #offset: offset,
        }),
        returnValue: _i5.Future<List<_i8.JournalEntity>>.value(
          <_i8.JournalEntity>[],
        ),
      ) as _i5.Future<List<_i8.JournalEntity>>);

  @override
  _i5.Future<List<_i8.JournalEntity>> getJournalEntitiesForIds(
    Set<String>? ids,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#getJournalEntitiesForIds, [ids]),
        returnValue: _i5.Future<List<_i8.JournalEntity>>.value(
          <_i8.JournalEntity>[],
        ),
      ) as _i5.Future<List<_i8.JournalEntity>>);

  @override
  _i5.Future<List<String>> getJournalEntityIds({
    required List<String>? types,
    required List<bool>? starredStatuses,
    required List<bool>? privateStatuses,
    required List<int>? flaggedStatuses,
    required List<String>? ids,
    int? limit = 500,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getJournalEntityIds, [], {
          #types: types,
          #starredStatuses: starredStatuses,
          #privateStatuses: privateStatuses,
          #flaggedStatuses: flaggedStatuses,
          #ids: ids,
          #limit: limit,
          #offset: offset,
        }),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<List<_i8.JournalEntity>> getTasks({
    required List<bool>? starredStatuses,
    required List<String>? taskStatuses,
    required List<String>? categoryIds,
    List<String>? ids,
    int? limit = 500,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getTasks, [], {
          #starredStatuses: starredStatuses,
          #taskStatuses: taskStatuses,
          #categoryIds: categoryIds,
          #ids: ids,
          #limit: limit,
          #offset: offset,
        }),
        returnValue: _i5.Future<List<_i8.JournalEntity>>.value(
          <_i8.JournalEntity>[],
        ),
      ) as _i5.Future<List<_i8.JournalEntity>>);

  @override
  _i5.Future<List<String>> getTasksIds({
    required List<bool>? starredStatuses,
    required List<String>? taskStatuses,
    List<String>? ids,
    int? limit = 500,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getTasksIds, [], {
          #starredStatuses: starredStatuses,
          #taskStatuses: taskStatuses,
          #ids: ids,
          #limit: limit,
          #offset: offset,
        }),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<int> getWipCount() => (super.noSuchMethod(
        Invocation.method(#getWipCount, []),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.FutureOr<List<String>> getSortedLinkedEntityIds(
    List<String>? linkedIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#getSortedLinkedEntityIds, [linkedIds]),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.FutureOr<List<String>>);

  @override
  _i5.Future<List<_i8.JournalEntity>> getLinkedEntities(String? linkedFrom) =>
      (super.noSuchMethod(
        Invocation.method(#getLinkedEntities, [linkedFrom]),
        returnValue: _i5.Future<List<_i8.JournalEntity>>.value(
          <_i8.JournalEntity>[],
        ),
      ) as _i5.Future<List<_i8.JournalEntity>>);

  @override
  _i5.Future<List<_i8.JournalEntity>> sortedTextEntries({
    required DateTime? rangeStart,
    required DateTime? rangeEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#sortedTextEntries, [], {
          #rangeStart: rangeStart,
          #rangeEnd: rangeEnd,
        }),
        returnValue: _i5.Future<List<_i8.JournalEntity>>.value(
          <_i8.JournalEntity>[],
        ),
      ) as _i5.Future<List<_i8.JournalEntity>>);

  @override
  _i5.Future<List<_i8.JournalEntity>> sortedCalendarEntries({
    required DateTime? rangeStart,
    required DateTime? rangeEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#sortedCalendarEntries, [], {
          #rangeStart: rangeStart,
          #rangeEnd: rangeEnd,
        }),
        returnValue: _i5.Future<List<_i8.JournalEntity>>.value(
          <_i8.JournalEntity>[],
        ),
      ) as _i5.Future<List<_i8.JournalEntity>>);

  @override
  _i5.Future<int> getTaggedCount() => (super.noSuchMethod(
        Invocation.method(#getTaggedCount, []),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getJournalCount() => (super.noSuchMethod(
        Invocation.method(#getJournalCount, []),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Stream<Set<_i3.ConfigFlag>> watchConfigFlags() => (super.noSuchMethod(
        Invocation.method(#watchConfigFlags, []),
        returnValue: _i5.Stream<Set<_i3.ConfigFlag>>.empty(),
      ) as _i5.Stream<Set<_i3.ConfigFlag>>);

  @override
  _i5.Stream<Set<String>> watchActiveConfigFlagNames() => (super.noSuchMethod(
        Invocation.method(#watchActiveConfigFlagNames, []),
        returnValue: _i5.Stream<Set<String>>.empty(),
      ) as _i5.Stream<Set<String>>);

  @override
  bool findConfigFlag(String? flagName, List<_i3.ConfigFlag>? flags) =>
      (super.noSuchMethod(
        Invocation.method(#findConfigFlag, [flagName, flags]),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> purgeDeletedFiles() => (super.noSuchMethod(
        Invocation.method(#purgeDeletedFiles, []),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<double> purgeDeleted({bool? backup = true}) => (super.noSuchMethod(
        Invocation.method(#purgeDeleted, [], {#backup: backup}),
        returnValue: _i5.Stream<double>.empty(),
      ) as _i5.Stream<double>);

  @override
  _i5.Future<bool> getConfigFlag(String? flagName) => (super.noSuchMethod(
        Invocation.method(#getConfigFlag, [flagName]),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Stream<bool> watchConfigFlag(String? flagName) => (super.noSuchMethod(
        Invocation.method(#watchConfigFlag, [flagName]),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  _i5.Future<_i3.ConfigFlag?> getConfigFlagByName(String? flagName) =>
      (super.noSuchMethod(
        Invocation.method(#getConfigFlagByName, [flagName]),
        returnValue: _i5.Future<_i3.ConfigFlag?>.value(),
      ) as _i5.Future<_i3.ConfigFlag?>);

  @override
  _i5.Future<void> insertFlagIfNotExists(_i3.ConfigFlag? configFlag) =>
      (super.noSuchMethod(
        Invocation.method(#insertFlagIfNotExists, [configFlag]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> upsertConfigFlag(_i3.ConfigFlag? configFlag) =>
      (super.noSuchMethod(
        Invocation.method(#upsertConfigFlag, [configFlag]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> toggleConfigFlag(String? flagName) => (super.noSuchMethod(
        Invocation.method(#toggleConfigFlag, [flagName]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setConfigFlag(String? flagName, {required bool? value}) =>
      (super.noSuchMethod(
        Invocation.method(#setConfigFlag, [flagName], {#value: value}),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getCountImportFlagEntries() => (super.noSuchMethod(
        Invocation.method(#getCountImportFlagEntries, []),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getTasksCount({
    List<String>? statuses = const ['IN PROGRESS'],
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getTasksCount, [], {#statuses: statuses}),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Stream<List<_i9.MeasurableDataType>> watchMeasurableDataTypes() =>
      (super.noSuchMethod(
        Invocation.method(#watchMeasurableDataTypes, []),
        returnValue: _i5.Stream<List<_i9.MeasurableDataType>>.empty(),
      ) as _i5.Stream<List<_i9.MeasurableDataType>>);

  @override
  _i5.Stream<_i9.MeasurableDataType?> watchMeasurableDataTypeById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#watchMeasurableDataTypeById, [id]),
        returnValue: _i5.Stream<_i9.MeasurableDataType?>.empty(),
      ) as _i5.Stream<_i9.MeasurableDataType?>);

  @override
  _i5.Future<_i9.MeasurableDataType?> getMeasurableDataTypeById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#getMeasurableDataTypeById, [id]),
        returnValue: _i5.Future<_i9.MeasurableDataType?>.value(),
      ) as _i5.Future<_i9.MeasurableDataType?>);

  @override
  _i5.Future<List<_i8.JournalEntity>> getMeasurementsByType({
    required String? type,
    required DateTime? rangeStart,
    required DateTime? rangeEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getMeasurementsByType, [], {
          #type: type,
          #rangeStart: rangeStart,
          #rangeEnd: rangeEnd,
        }),
        returnValue: _i5.Future<List<_i8.JournalEntity>>.value(
          <_i8.JournalEntity>[],
        ),
      ) as _i5.Future<List<_i8.JournalEntity>>);

  @override
  _i5.Future<List<_i8.JournalEntity>> getHabitCompletionsByHabitId({
    required String? habitId,
    required DateTime? rangeStart,
    required DateTime? rangeEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getHabitCompletionsByHabitId, [], {
          #habitId: habitId,
          #rangeStart: rangeStart,
          #rangeEnd: rangeEnd,
        }),
        returnValue: _i5.Future<List<_i8.JournalEntity>>.value(
          <_i8.JournalEntity>[],
        ),
      ) as _i5.Future<List<_i8.JournalEntity>>);

  @override
  _i5.Future<List<_i8.JournalEntity>> getHabitCompletionsInRange({
    required DateTime? rangeStart,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getHabitCompletionsInRange, [], {
          #rangeStart: rangeStart,
        }),
        returnValue: _i5.Future<List<_i8.JournalEntity>>.value(
          <_i8.JournalEntity>[],
        ),
      ) as _i5.Future<List<_i8.JournalEntity>>);

  @override
  _i5.Future<List<_i8.JournalEntity>> getQuantitativeByType({
    required String? type,
    required DateTime? rangeStart,
    required DateTime? rangeEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getQuantitativeByType, [], {
          #type: type,
          #rangeStart: rangeStart,
          #rangeEnd: rangeEnd,
        }),
        returnValue: _i5.Future<List<_i8.JournalEntity>>.value(
          <_i8.JournalEntity>[],
        ),
      ) as _i5.Future<List<_i8.JournalEntity>>);

  @override
  _i5.Future<_i8.QuantitativeEntry?> latestQuantitativeByType(String? type) =>
      (super.noSuchMethod(
        Invocation.method(#latestQuantitativeByType, [type]),
        returnValue: _i5.Future<_i8.QuantitativeEntry?>.value(),
      ) as _i5.Future<_i8.QuantitativeEntry?>);

  @override
  _i5.Future<_i8.WorkoutEntry?> latestWorkout() => (super.noSuchMethod(
        Invocation.method(#latestWorkout, []),
        returnValue: _i5.Future<_i8.WorkoutEntry?>.value(),
      ) as _i5.Future<_i8.WorkoutEntry?>);

  @override
  _i5.Future<List<_i8.JournalEntity>> getSurveyCompletionsByType({
    required String? type,
    required DateTime? rangeStart,
    required DateTime? rangeEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getSurveyCompletionsByType, [], {
          #type: type,
          #rangeStart: rangeStart,
          #rangeEnd: rangeEnd,
        }),
        returnValue: _i5.Future<List<_i8.JournalEntity>>.value(
          <_i8.JournalEntity>[],
        ),
      ) as _i5.Future<List<_i8.JournalEntity>>);

  @override
  _i5.Future<List<_i8.JournalEntity>> getWorkouts({
    required DateTime? rangeStart,
    required DateTime? rangeEnd,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#getWorkouts, [], {
          #rangeStart: rangeStart,
          #rangeEnd: rangeEnd,
        }),
        returnValue: _i5.Future<List<_i8.JournalEntity>>.value(
          <_i8.JournalEntity>[],
        ),
      ) as _i5.Future<List<_i8.JournalEntity>>);

  @override
  _i5.Stream<List<_i3.Conflict>> watchConflicts(
    _i3.ConflictStatus? status, {
    int? limit = 1000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#watchConflicts, [status], {#limit: limit}),
        returnValue: _i5.Stream<List<_i3.Conflict>>.empty(),
      ) as _i5.Stream<List<_i3.Conflict>>);

  @override
  _i5.Stream<List<_i3.Conflict>> watchConflictById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#watchConflictById, [id]),
        returnValue: _i5.Stream<List<_i3.Conflict>>.empty(),
      ) as _i5.Stream<List<_i3.Conflict>>);

  @override
  _i5.Stream<List<_i10.TagEntity>> watchTags() => (super.noSuchMethod(
        Invocation.method(#watchTags, []),
        returnValue: _i5.Stream<List<_i10.TagEntity>>.empty(),
      ) as _i5.Stream<List<_i10.TagEntity>>);

  @override
  _i5.Stream<List<_i9.DashboardDefinition>> watchDashboards() =>
      (super.noSuchMethod(
        Invocation.method(#watchDashboards, []),
        returnValue: _i5.Stream<List<_i9.DashboardDefinition>>.empty(),
      ) as _i5.Stream<List<_i9.DashboardDefinition>>);

  @override
  _i5.Stream<_i9.DashboardDefinition?> watchDashboardById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#watchDashboardById, [id]),
        returnValue: _i5.Stream<_i9.DashboardDefinition?>.empty(),
      ) as _i5.Stream<_i9.DashboardDefinition?>);

  @override
  _i5.Stream<List<_i9.HabitDefinition>> watchHabitDefinitions() =>
      (super.noSuchMethod(
        Invocation.method(#watchHabitDefinitions, []),
        returnValue: _i5.Stream<List<_i9.HabitDefinition>>.empty(),
      ) as _i5.Stream<List<_i9.HabitDefinition>>);

  @override
  _i5.Stream<List<_i9.CategoryDefinition>> watchCategories() =>
      (super.noSuchMethod(
        Invocation.method(#watchCategories, []),
        returnValue: _i5.Stream<List<_i9.CategoryDefinition>>.empty(),
      ) as _i5.Stream<List<_i9.CategoryDefinition>>);

  @override
  _i5.Stream<_i9.CategoryDefinition?> watchCategoryById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#watchCategoryById, [id]),
        returnValue: _i5.Stream<_i9.CategoryDefinition?>.empty(),
      ) as _i5.Stream<_i9.CategoryDefinition?>);

  @override
  _i5.Stream<_i9.HabitDefinition?> watchHabitById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#watchHabitById, [id]),
        returnValue: _i5.Stream<_i9.HabitDefinition?>.empty(),
      ) as _i5.Stream<_i9.HabitDefinition?>);

  @override
  _i5.Future<List<_i10.TagEntity>> getMatchingTags(
    String? match, {
    int? limit = 10,
    bool? inactive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMatchingTags,
          [match],
          {#limit: limit, #inactive: inactive},
        ),
        returnValue: _i5.Future<List<_i10.TagEntity>>.value(
          <_i10.TagEntity>[],
        ),
      ) as _i5.Future<List<_i10.TagEntity>>);

  @override
  _i5.Future<int> resolveConflict(_i3.Conflict? conflict) =>
      (super.noSuchMethod(
        Invocation.method(#resolveConflict, [conflict]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> upsertMeasurableDataType(
    _i9.MeasurableDataType? entityDefinition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#upsertMeasurableDataType, [entityDefinition]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> upsertTagEntity(_i10.TagEntity? tag) => (super.noSuchMethod(
        Invocation.method(#upsertTagEntity, [tag]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> upsertHabitDefinition(_i9.HabitDefinition? habitDefinition) =>
      (super.noSuchMethod(
        Invocation.method(#upsertHabitDefinition, [habitDefinition]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> upsertDashboardDefinition(
    _i9.DashboardDefinition? dashboardDefinition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#upsertDashboardDefinition, [
          dashboardDefinition,
        ]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> upsertCategoryDefinition(
    _i9.CategoryDefinition? categoryDefinition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#upsertCategoryDefinition, [categoryDefinition]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i11.EntryLink>> linksForEntryIds(Set<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(#linksForEntryIds, [ids]),
        returnValue: _i5.Future<List<_i11.EntryLink>>.value(
          <_i11.EntryLink>[],
        ),
      ) as _i5.Future<List<_i11.EntryLink>>);

  @override
  _i5.Future<int> upsertEntryLink(_i11.EntryLink? link) => (super.noSuchMethod(
        Invocation.method(#upsertEntryLink, [link]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> upsertEntityDefinition(
    _i9.EntityDefinition? entityDefinition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#upsertEntityDefinition, [entityDefinition]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i2.Selectable<_i3.ConfigFlag> listConfigFlags() => (super.noSuchMethod(
        Invocation.method(#listConfigFlags, []),
        returnValue: _FakeSelectable_20<_i3.ConfigFlag>(
          this,
          Invocation.method(#listConfigFlags, []),
        ),
      ) as _i2.Selectable<_i3.ConfigFlag>);

  @override
  _i2.Selectable<_i3.ConfigFlag> configFlagByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(#configFlagByName, [name]),
        returnValue: _FakeSelectable_20<_i3.ConfigFlag>(
          this,
          Invocation.method(#configFlagByName, [name]),
        ),
      ) as _i2.Selectable<_i3.ConfigFlag>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> filteredJournal(
    List<String>? types,
    List<bool>? starredStatuses,
    List<bool>? privateStatuses,
    List<int>? flaggedStatuses,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#filteredJournal, [
          types,
          starredStatuses,
          privateStatuses,
          flaggedStatuses,
          limit,
          offset,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#filteredJournal, [
            types,
            starredStatuses,
            privateStatuses,
            flaggedStatuses,
            limit,
            offset,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> filteredJournalByCategories(
    List<String>? types,
    List<bool>? starredStatuses,
    List<bool>? privateStatuses,
    List<int>? flaggedStatuses,
    List<String>? categories,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#filteredJournalByCategories, [
          types,
          starredStatuses,
          privateStatuses,
          flaggedStatuses,
          categories,
          limit,
          offset,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#filteredJournalByCategories, [
            types,
            starredStatuses,
            privateStatuses,
            flaggedStatuses,
            categories,
            limit,
            offset,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<String> filteredJournalIds(
    List<String>? types,
    List<bool>? starredStatuses,
    List<bool>? privateStatuses,
    List<int>? flaggedStatuses,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#filteredJournalIds, [
          types,
          starredStatuses,
          privateStatuses,
          flaggedStatuses,
          limit,
          offset,
        ]),
        returnValue: _FakeSelectable_20<String>(
          this,
          Invocation.method(#filteredJournalIds, [
            types,
            starredStatuses,
            privateStatuses,
            flaggedStatuses,
            limit,
            offset,
          ]),
        ),
      ) as _i2.Selectable<String>);

  @override
  _i2.Selectable<String> filteredJournalIds2(
    List<String>? types,
    List<String>? ids,
    List<bool>? starredStatuses,
    List<bool>? privateStatuses,
    List<int>? flaggedStatuses,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#filteredJournalIds2, [
          types,
          ids,
          starredStatuses,
          privateStatuses,
          flaggedStatuses,
          limit,
          offset,
        ]),
        returnValue: _FakeSelectable_20<String>(
          this,
          Invocation.method(#filteredJournalIds2, [
            types,
            ids,
            starredStatuses,
            privateStatuses,
            flaggedStatuses,
            limit,
            offset,
          ]),
        ),
      ) as _i2.Selectable<String>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> filteredByTagJournal(
    List<String>? types,
    List<String>? ids,
    List<bool>? starredStatuses,
    List<bool>? privateStatuses,
    List<int>? flaggedStatuses,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#filteredByTagJournal, [
          types,
          ids,
          starredStatuses,
          privateStatuses,
          flaggedStatuses,
          limit,
          offset,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#filteredByTagJournal, [
            types,
            ids,
            starredStatuses,
            privateStatuses,
            flaggedStatuses,
            limit,
            offset,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> filteredByTaggedWithId(
    String? tagId,
    DateTime? rangeStart,
    DateTime? rangeEnd,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#filteredByTaggedWithId, [
          tagId,
          rangeStart,
          rangeEnd,
          limit,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#filteredByTaggedWithId, [
            tagId,
            rangeStart,
            rangeEnd,
            limit,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> filteredByTaggedWithIds(
    List<String>? tagIds,
    DateTime? rangeStart,
    DateTime? rangeEnd,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#filteredByTaggedWithIds, [
          tagIds,
          rangeStart,
          rangeEnd,
          limit,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#filteredByTaggedWithIds, [
            tagIds,
            rangeStart,
            rangeEnd,
            limit,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> sortedTextEntriesInRange(
    DateTime? rangeStart,
    DateTime? rangeEnd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#sortedTextEntriesInRange, [
          rangeStart,
          rangeEnd,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#sortedTextEntriesInRange, [
            rangeStart,
            rangeEnd,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> sortedCalenderEntriesInRange(
    DateTime? rangeStart,
    DateTime? rangeEnd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#sortedCalenderEntriesInRange, [
          rangeStart,
          rangeEnd,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#sortedCalenderEntriesInRange, [
            rangeStart,
            rangeEnd,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> filteredByTagMatch(
    String? match,
    DateTime? rangeStart,
    DateTime? rangeEnd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#filteredByTagMatch, [
          match,
          rangeStart,
          rangeEnd,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#filteredByTagMatch, [
            match,
            rangeStart,
            rangeEnd,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> filteredTasks(
    List<String>? types,
    List<bool>? starredStatuses,
    List<String?>? taskStatuses,
    List<String>? categories,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#filteredTasks, [
          types,
          starredStatuses,
          taskStatuses,
          categories,
          limit,
          offset,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#filteredTasks, [
            types,
            starredStatuses,
            taskStatuses,
            categories,
            limit,
            offset,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> filteredTasks2(
    List<String>? types,
    List<String>? ids,
    List<bool>? starredStatuses,
    List<String?>? taskStatuses,
    List<String>? categories,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#filteredTasks2, [
          types,
          ids,
          starredStatuses,
          taskStatuses,
          categories,
          limit,
          offset,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#filteredTasks2, [
            types,
            ids,
            starredStatuses,
            taskStatuses,
            categories,
            limit,
            offset,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<String> filteredTaskIds(
    List<String>? types,
    List<bool>? starredStatuses,
    List<String?>? taskStatuses,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#filteredTaskIds, [
          types,
          starredStatuses,
          taskStatuses,
          limit,
          offset,
        ]),
        returnValue: _FakeSelectable_20<String>(
          this,
          Invocation.method(#filteredTaskIds, [
            types,
            starredStatuses,
            taskStatuses,
            limit,
            offset,
          ]),
        ),
      ) as _i2.Selectable<String>);

  @override
  _i2.Selectable<String> filteredTaskIds2(
    List<String>? types,
    List<String>? ids,
    List<bool>? starredStatuses,
    List<String?>? taskStatuses,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#filteredTaskIds2, [
          types,
          ids,
          starredStatuses,
          taskStatuses,
          limit,
          offset,
        ]),
        returnValue: _FakeSelectable_20<String>(
          this,
          Invocation.method(#filteredTaskIds2, [
            types,
            ids,
            starredStatuses,
            taskStatuses,
            limit,
            offset,
          ]),
        ),
      ) as _i2.Selectable<String>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> orderedJournal(int? limit, int? offset) =>
      (super.noSuchMethod(
        Invocation.method(#orderedJournal, [limit, offset]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#orderedJournal, [limit, offset]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> orderedJournalInterval(
    DateTime? start,
    DateTime? end,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#orderedJournalInterval, [
          start,
          end,
          limit,
          offset,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#orderedJournalInterval, [
            start,
            end,
            limit,
            offset,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> orderedAudioEntries(
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#orderedAudioEntries, [limit, offset]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#orderedAudioEntries, [limit, offset]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> entriesFlaggedImport(int? limit) =>
      (super.noSuchMethod(
        Invocation.method(#entriesFlaggedImport, [limit]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#entriesFlaggedImport, [limit]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.Conflict> conflictsByStatus(int? status, int? limit) =>
      (super.noSuchMethod(
        Invocation.method(#conflictsByStatus, [status, limit]),
        returnValue: _FakeSelectable_20<_i3.Conflict>(
          this,
          Invocation.method(#conflictsByStatus, [status, limit]),
        ),
      ) as _i2.Selectable<_i3.Conflict>);

  @override
  _i2.Selectable<_i3.Conflict> conflictsById(String? id) => (super.noSuchMethod(
        Invocation.method(#conflictsById, [id]),
        returnValue: _FakeSelectable_20<_i3.Conflict>(
          this,
          Invocation.method(#conflictsById, [id]),
        ),
      ) as _i2.Selectable<_i3.Conflict>);

  @override
  _i2.Selectable<_i3.MeasurableDbEntity> activeMeasurableTypes() =>
      (super.noSuchMethod(
        Invocation.method(#activeMeasurableTypes, []),
        returnValue: _FakeSelectable_20<_i3.MeasurableDbEntity>(
          this,
          Invocation.method(#activeMeasurableTypes, []),
        ),
      ) as _i2.Selectable<_i3.MeasurableDbEntity>);

  @override
  _i2.Selectable<_i3.MeasurableDbEntity> measurableTypeById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#measurableTypeById, [id]),
        returnValue: _FakeSelectable_20<_i3.MeasurableDbEntity>(
          this,
          Invocation.method(#measurableTypeById, [id]),
        ),
      ) as _i2.Selectable<_i3.MeasurableDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> measurementsByType(
    String? subtype,
    DateTime? rangeStart,
    DateTime? rangeEnd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#measurementsByType, [
          subtype,
          rangeStart,
          rangeEnd,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#measurementsByType, [
            subtype,
            rangeStart,
            rangeEnd,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> habitCompletionsByHabitId(
    String? habitId,
    DateTime? rangeStart,
    DateTime? rangeEnd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#habitCompletionsByHabitId, [
          habitId,
          rangeStart,
          rangeEnd,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#habitCompletionsByHabitId, [
            habitId,
            rangeStart,
            rangeEnd,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> habitCompletionsInRange(
    DateTime? rangeStart,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#habitCompletionsInRange, [rangeStart]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#habitCompletionsInRange, [rangeStart]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> quantitativeByType(
    String? subtype,
    DateTime? rangeStart,
    DateTime? rangeEnd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#quantitativeByType, [
          subtype,
          rangeStart,
          rangeEnd,
        ]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#quantitativeByType, [
            subtype,
            rangeStart,
            rangeEnd,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> latestQuantByType(String? subtype) =>
      (super.noSuchMethod(
        Invocation.method(#latestQuantByType, [subtype]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#latestQuantByType, [subtype]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> workouts(
    DateTime? rangeStart,
    DateTime? rangeEnd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#workouts, [rangeStart, rangeEnd]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#workouts, [rangeStart, rangeEnd]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> findLatestWorkout() =>
      (super.noSuchMethod(
        Invocation.method(#findLatestWorkout, []),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#findLatestWorkout, []),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> surveysByType(
    String? subtype,
    DateTime? rangeStart,
    DateTime? rangeEnd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#surveysByType, [subtype, rangeStart, rangeEnd]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#surveysByType, [
            subtype,
            rangeStart,
            rangeEnd,
          ]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<int> countJournalEntries() => (super.noSuchMethod(
        Invocation.method(#countJournalEntries, []),
        returnValue: _FakeSelectable_20<int>(
          this,
          Invocation.method(#countJournalEntries, []),
        ),
      ) as _i2.Selectable<int>);

  @override
  _i2.Selectable<int> countImportFlagEntries() => (super.noSuchMethod(
        Invocation.method(#countImportFlagEntries, []),
        returnValue: _FakeSelectable_20<int>(
          this,
          Invocation.method(#countImportFlagEntries, []),
        ),
      ) as _i2.Selectable<int>);

  @override
  _i2.Selectable<int> countInProgressTasks(List<String?>? taskStatuses) =>
      (super.noSuchMethod(
        Invocation.method(#countInProgressTasks, [taskStatuses]),
        returnValue: _FakeSelectable_20<int>(
          this,
          Invocation.method(#countInProgressTasks, [taskStatuses]),
        ),
      ) as _i2.Selectable<int>);

  @override
  _i2.Selectable<_i3.TagDbEntity> allTagEntities() => (super.noSuchMethod(
        Invocation.method(#allTagEntities, []),
        returnValue: _FakeSelectable_20<_i3.TagDbEntity>(
          this,
          Invocation.method(#allTagEntities, []),
        ),
      ) as _i2.Selectable<_i3.TagDbEntity>);

  @override
  _i2.Selectable<_i3.DashboardDefinitionDbEntity> allDashboards() =>
      (super.noSuchMethod(
        Invocation.method(#allDashboards, []),
        returnValue: _FakeSelectable_20<_i3.DashboardDefinitionDbEntity>(
          this,
          Invocation.method(#allDashboards, []),
        ),
      ) as _i2.Selectable<_i3.DashboardDefinitionDbEntity>);

  @override
  _i2.Selectable<_i3.DashboardDefinitionDbEntity> dashboardById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#dashboardById, [id]),
        returnValue: _FakeSelectable_20<_i3.DashboardDefinitionDbEntity>(
          this,
          Invocation.method(#dashboardById, [id]),
        ),
      ) as _i2.Selectable<_i3.DashboardDefinitionDbEntity>);

  @override
  _i2.Selectable<_i3.HabitDefinitionDbEntity> allHabitDefinitions() =>
      (super.noSuchMethod(
        Invocation.method(#allHabitDefinitions, []),
        returnValue: _FakeSelectable_20<_i3.HabitDefinitionDbEntity>(
          this,
          Invocation.method(#allHabitDefinitions, []),
        ),
      ) as _i2.Selectable<_i3.HabitDefinitionDbEntity>);

  @override
  _i2.Selectable<_i3.HabitDefinitionDbEntity> habitById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#habitById, [id]),
        returnValue: _FakeSelectable_20<_i3.HabitDefinitionDbEntity>(
          this,
          Invocation.method(#habitById, [id]),
        ),
      ) as _i2.Selectable<_i3.HabitDefinitionDbEntity>);

  @override
  _i2.Selectable<_i3.CategoryDefinitionDbEntity> allCategoryDefinitions() =>
      (super.noSuchMethod(
        Invocation.method(#allCategoryDefinitions, []),
        returnValue: _FakeSelectable_20<_i3.CategoryDefinitionDbEntity>(
          this,
          Invocation.method(#allCategoryDefinitions, []),
        ),
      ) as _i2.Selectable<_i3.CategoryDefinitionDbEntity>);

  @override
  _i2.Selectable<_i3.CategoryDefinitionDbEntity> categoryById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#categoryById, [id]),
        returnValue: _FakeSelectable_20<_i3.CategoryDefinitionDbEntity>(
          this,
          Invocation.method(#categoryById, [id]),
        ),
      ) as _i2.Selectable<_i3.CategoryDefinitionDbEntity>);

  @override
  _i2.Selectable<_i3.TagDbEntity> matchingTagEntities(
    String? match,
    bool? inactive,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#matchingTagEntities, [match, inactive, limit]),
        returnValue: _FakeSelectable_20<_i3.TagDbEntity>(
          this,
          Invocation.method(#matchingTagEntities, [match, inactive, limit]),
        ),
      ) as _i2.Selectable<_i3.TagDbEntity>);

  @override
  _i5.Future<int> deleteTaggedForId(String? id) => (super.noSuchMethod(
        Invocation.method(#deleteTaggedForId, [id]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> purgeDeletedDashboards() => (super.noSuchMethod(
        Invocation.method(#purgeDeletedDashboards, []),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> purgeDeletedMeasurables() => (super.noSuchMethod(
        Invocation.method(#purgeDeletedMeasurables, []),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> purgeDeletedTagEntities() => (super.noSuchMethod(
        Invocation.method(#purgeDeletedTagEntities, []),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> purgeDeletedJournalEntities() => (super.noSuchMethod(
        Invocation.method(#purgeDeletedJournalEntities, []),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> deleteTagged() => (super.noSuchMethod(
        Invocation.method(#deleteTagged, []),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i2.Selectable<String> entryIdsForTagId(String? tagId) => (super.noSuchMethod(
        Invocation.method(#entryIdsForTagId, [tagId]),
        returnValue: _FakeSelectable_20<String>(
          this,
          Invocation.method(#entryIdsForTagId, [tagId]),
        ),
      ) as _i2.Selectable<String>);

  @override
  _i2.Selectable<int> countTagged() => (super.noSuchMethod(
        Invocation.method(#countTagged, []),
        returnValue: _FakeSelectable_20<int>(
          this,
          Invocation.method(#countTagged, []),
        ),
      ) as _i2.Selectable<int>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> linkedJournalEntities(String? fromId) =>
      (super.noSuchMethod(
        Invocation.method(#linkedJournalEntities, [fromId]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#linkedJournalEntities, [fromId]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<String> journalEntityIdsByDateFromDesc(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(#journalEntityIdsByDateFromDesc, [ids]),
        returnValue: _FakeSelectable_20<String>(
          this,
          Invocation.method(#journalEntityIdsByDateFromDesc, [ids]),
        ),
      ) as _i2.Selectable<String>);

  @override
  _i2.Selectable<_i3.LinkedDbEntry> linksForIds(List<String>? toIds) =>
      (super.noSuchMethod(
        Invocation.method(#linksForIds, [toIds]),
        returnValue: _FakeSelectable_20<_i3.LinkedDbEntry>(
          this,
          Invocation.method(#linksForIds, [toIds]),
        ),
      ) as _i2.Selectable<_i3.LinkedDbEntry>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> entriesForIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(#entriesForIds, [ids]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#entriesForIds, [ids]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> journalEntitiesByIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(#journalEntitiesByIds, [ids]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#journalEntitiesByIds, [ids]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i2.Selectable<String> linkedJournalEntityIds(
    String? fromId,
    List<bool?>? hidden,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#linkedJournalEntityIds, [fromId, hidden]),
        returnValue: _FakeSelectable_20<String>(
          this,
          Invocation.method(#linkedJournalEntityIds, [fromId, hidden]),
        ),
      ) as _i2.Selectable<String>);

  @override
  _i2.Selectable<_i3.LinkedDbEntry> linksFromId(
    String? fromId,
    List<bool?>? hidden,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#linksFromId, [fromId, hidden]),
        returnValue: _FakeSelectable_20<_i3.LinkedDbEntry>(
          this,
          Invocation.method(#linksFromId, [fromId, hidden]),
        ),
      ) as _i2.Selectable<_i3.LinkedDbEntry>);

  @override
  _i2.Selectable<_i3.JournalDbEntity> linkedToJournalEntities(String? toId) =>
      (super.noSuchMethod(
        Invocation.method(#linkedToJournalEntities, [toId]),
        returnValue: _FakeSelectable_20<_i3.JournalDbEntity>(
          this,
          Invocation.method(#linkedToJournalEntities, [toId]),
        ),
      ) as _i2.Selectable<_i3.JournalDbEntity>);

  @override
  _i5.Future<int> deleteLink(String? fromId, String? toId) =>
      (super.noSuchMethod(
        Invocation.method(#deleteLink, [fromId, toId]),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i2.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(#createMigrator, []),
        returnValue: _FakeMigrator_21(
          this,
          Invocation.method(#createMigrator, []),
        ),
      ) as _i2.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i2.QueryExecutor? executor,
    _i2.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#beforeOpen, [executor, details]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(#close, []),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#createStream, [stmt]),
        returnValue: _i5.Stream<T>.empty(),
      ) as _i5.Stream<T>);

  @override
  T alias<T, D>(_i2.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
        Invocation.method(#alias, [table, alias]),
        returnValue: _i6.dummyValue<T>(
          this,
          Invocation.method(#alias, [table, alias]),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(#notifyUpdates, [updates]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<Set<_i2.TableUpdate>> tableUpdates([
    _i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
        Invocation.method(#tableUpdates, [query]),
        returnValue: _i5.Stream<Set<_i2.TableUpdate>>.empty(),
      ) as _i5.Stream<Set<_i2.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
    _i5.FutureOr<T> Function(_i2.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#doWhenOpened, [fn]),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(#doWhenOpened, [fn]),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_22<T>(this, Invocation.method(#doWhenOpened, [fn])),
      ) as _i5.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#into, [table]),
        returnValue: _FakeInsertStatement_23<T, D>(
          this,
          Invocation.method(#into, [table]),
        ),
      ) as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
    _i2.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#update, [table]),
        returnValue: _FakeUpdateStatement_24<Tbl, R>(
          this,
          Invocation.method(#update, [table]),
        ),
      ) as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#select, [table], {#distinct: distinct}),
        returnValue: _FakeSimpleSelectStatement_25<T, R>(
          this,
          Invocation.method(#select, [table], {#distinct: distinct}),
        ),
      ) as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#selectOnly, [table], {#distinct: distinct}),
        returnValue: _FakeJoinedSelectStatement_26<T, R>(
          this,
          Invocation.method(#selectOnly, [table], {#distinct: distinct}),
        ),
      ) as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
    Iterable<_i2.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#selectExpressions, [columns]),
        returnValue: _FakeBaseSelectStatement_27<_i2.TypedResult>(
          this,
          Invocation.method(#selectExpressions, [columns]),
        ),
      ) as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#delete, [table]),
        returnValue: _FakeDeleteStatement_28<T, D>(
          this,
          Invocation.method(#delete, [table]),
        ),
      ) as _i2.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {#variables: variables, #updates: updates},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<List<_i2.QueryRow>>.value(<_i2.QueryRow>[]),
      ) as _i5.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {#variables: variables, #readsFrom: readsFrom},
        ),
        returnValue: _FakeSelectable_20<_i2.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {#variables: variables, #readsFrom: readsFrom},
          ),
        ),
      ) as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {#variables: variables, #readsFrom: readsFrom},
        ),
        returnValue: _FakeSelectable_20<_i2.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {#variables: variables, #readsFrom: readsFrom},
          ),
        ),
      ) as _i2.Selectable<_i2.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
        Invocation.method(#customStatement, [statement, args]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_22<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(#exclusively, [action]),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(#exclusively, [action]),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_22<T>(
              this,
              Invocation.method(#exclusively, [action]),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i2.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(#batch, [runInBatch]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWithInterceptor,
          [action],
          {#interceptor: interceptor},
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runWithInterceptor,
                  [action],
                  {#interceptor: interceptor},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_22<T>(
              this,
              Invocation.method(
                #runWithInterceptor,
                [action],
                {#interceptor: interceptor},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_29(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [table, insertable],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_29(
          this,
          Invocation.method(
            #$writeInsertable,
            [table, insertable],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i2.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) => (super.noSuchMethod(
        Invocation.method(#$expandVar, [start, amount]),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(#$expandVar, [start, amount]),
        ),
      ) as String);
}

/// A class which mocks [OutboxService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOutboxService extends _i1.Mock implements _i12.OutboxService {
  MockOutboxService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i13.OutboxItem>> getNextItems() => (super.noSuchMethod(
        Invocation.method(#getNextItems, []),
        returnValue: _i5.Future<List<_i13.OutboxItem>>.value(
          <_i13.OutboxItem>[],
        ),
      ) as _i5.Future<List<_i13.OutboxItem>>);

  @override
  _i5.Future<void> enqueueMessage(_i14.SyncMessage? syncMessage) =>
      (super.noSuchMethod(
        Invocation.method(#enqueueMessage, [syncMessage]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendNext() => (super.noSuchMethod(
        Invocation.method(#sendNext, []),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> enqueueNextSendRequest({
    Duration? delay = const Duration(milliseconds: 1),
  }) =>
      (super.noSuchMethod(
        Invocation.method(#enqueueNextSendRequest, [], {#delay: delay}),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [LoggingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggingService extends _i1.Mock implements _i15.LoggingService {
  MockLoggingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void listenToConfigFlag() => super.noSuchMethod(
        Invocation.method(#listenToConfigFlag, []),
        returnValueForMissingStub: null,
      );

  @override
  void captureEvent(
    dynamic event, {
    required String? domain,
    String? subDomain,
    _i16.InsightLevel? level = _i16.InsightLevel.info,
    _i16.InsightType? type = _i16.InsightType.log,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #captureEvent,
          [event],
          {#domain: domain, #subDomain: subDomain, #level: level, #type: type},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void captureException(
    dynamic exception, {
    required String? domain,
    String? subDomain,
    dynamic stackTrace,
    _i16.InsightLevel? level = _i16.InsightLevel.error,
    _i16.InsightType? type = _i16.InsightType.exception,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #captureException,
          [exception],
          {
            #domain: domain,
            #subDomain: subDomain,
            #stackTrace: stackTrace,
            #level: level,
            #type: type,
          },
        ),
        returnValueForMissingStub: null,
      );
}
