// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/ai/database/objectbox_embedding_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7733010829479720585),
    name: 'EmbeddingChunkEntity',
    lastPropertyId: const obx_int.IdUid(12, 2431739967825078836),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4818100322456678366),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8456946487932002352),
        name: 'embeddingKey',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 1704346918069046739),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1106036643557037878),
        name: 'entityId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 8038513102044490574),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5610878150348606962),
        name: 'chunkIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 985403409809708063),
        name: 'entityType',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 5530180604776325062),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5777238874657793844),
        name: 'modelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8476056733222980998),
        name: 'contentHash',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5623514757416898692),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6298161146123181181),
        name: 'categoryId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 1000760643470582643),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6347455455008508013),
        name: 'taskId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 1674130426089708390),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6606648515587880865),
        name: 'subtype',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 8023161639191114807),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2431739967825078836),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(7, 4134738425623489094),
        hnswParams: obx_int.ModelHnswParams(
          dimensions: 1024,
          neighborsPerNode: 30,
          indexingSearchCount: 200,
          distanceType: 2,
        ),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 7733010829479720585),
    lastIndexId: const obx_int.IdUid(7, 4134738425623489094),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    EmbeddingChunkEntity: obx_int.EntityDefinition<EmbeddingChunkEntity>(
      model: _entities[0],
      toOneRelations: (EmbeddingChunkEntity object) => [],
      toManyRelations: (EmbeddingChunkEntity object) => {},
      getId: (EmbeddingChunkEntity object) => object.id,
      setId: (EmbeddingChunkEntity object, int id) {
        object.id = id;
      },
      objectToFB: (EmbeddingChunkEntity object, fb.Builder fbb) {
        final embeddingKeyOffset = fbb.writeString(object.embeddingKey);
        final entityIdOffset = fbb.writeString(object.entityId);
        final entityTypeOffset = fbb.writeString(object.entityType);
        final modelIdOffset = fbb.writeString(object.modelId);
        final contentHashOffset = fbb.writeString(object.contentHash);
        final categoryIdOffset = fbb.writeString(object.categoryId);
        final taskIdOffset = fbb.writeString(object.taskId);
        final subtypeOffset = fbb.writeString(object.subtype);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, embeddingKeyOffset);
        fbb.addOffset(2, entityIdOffset);
        fbb.addInt64(3, object.chunkIndex);
        fbb.addOffset(4, entityTypeOffset);
        fbb.addOffset(5, modelIdOffset);
        fbb.addOffset(6, contentHashOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(8, categoryIdOffset);
        fbb.addOffset(9, taskIdOffset);
        fbb.addOffset(10, subtypeOffset);
        fbb.addOffset(11, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final embeddingKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final entityIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final chunkIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final entityTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final modelIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final contentHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          isUtc: true,
        );
        final categoryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final taskIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final subtypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final embeddingParam = const obx_int.Float32ListReader().vTableGet(
          buffer,
          rootOffset,
          26,
          Float32List(0),
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = EmbeddingChunkEntity(
          embeddingKey: embeddingKeyParam,
          entityId: entityIdParam,
          chunkIndex: chunkIndexParam,
          entityType: entityTypeParam,
          modelId: modelIdParam,
          contentHash: contentHashParam,
          createdAt: createdAtParam,
          categoryId: categoryIdParam,
          taskId: taskIdParam,
          subtype: subtypeParam,
          embedding: embeddingParam,
          id: idParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EmbeddingChunkEntity] entity fields to define ObjectBox queries.
class EmbeddingChunkEntity_ {
  /// See [EmbeddingChunkEntity.id].
  static final id = obx.QueryIntegerProperty<EmbeddingChunkEntity>(
    _entities[0].properties[0],
  );

  /// See [EmbeddingChunkEntity.embeddingKey].
  static final embeddingKey = obx.QueryStringProperty<EmbeddingChunkEntity>(
    _entities[0].properties[1],
  );

  /// See [EmbeddingChunkEntity.entityId].
  static final entityId = obx.QueryStringProperty<EmbeddingChunkEntity>(
    _entities[0].properties[2],
  );

  /// See [EmbeddingChunkEntity.chunkIndex].
  static final chunkIndex = obx.QueryIntegerProperty<EmbeddingChunkEntity>(
    _entities[0].properties[3],
  );

  /// See [EmbeddingChunkEntity.entityType].
  static final entityType = obx.QueryStringProperty<EmbeddingChunkEntity>(
    _entities[0].properties[4],
  );

  /// See [EmbeddingChunkEntity.modelId].
  static final modelId = obx.QueryStringProperty<EmbeddingChunkEntity>(
    _entities[0].properties[5],
  );

  /// See [EmbeddingChunkEntity.contentHash].
  static final contentHash = obx.QueryStringProperty<EmbeddingChunkEntity>(
    _entities[0].properties[6],
  );

  /// See [EmbeddingChunkEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<EmbeddingChunkEntity>(
    _entities[0].properties[7],
  );

  /// See [EmbeddingChunkEntity.categoryId].
  static final categoryId = obx.QueryStringProperty<EmbeddingChunkEntity>(
    _entities[0].properties[8],
  );

  /// See [EmbeddingChunkEntity.taskId].
  static final taskId = obx.QueryStringProperty<EmbeddingChunkEntity>(
    _entities[0].properties[9],
  );

  /// See [EmbeddingChunkEntity.subtype].
  static final subtype = obx.QueryStringProperty<EmbeddingChunkEntity>(
    _entities[0].properties[10],
  );

  /// See [EmbeddingChunkEntity.embedding].
  static final embedding = obx.QueryHnswProperty<EmbeddingChunkEntity>(
    _entities[0].properties[11],
  );
}
