import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:lotti/features/tasks/ui/file_watcher_mixin.dart';
import 'package:lotti/utils/platform.dart' as platform_utils;
import 'package:path/path.dart' as p;

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('FileWatcherMixin', () {
    late Directory tempDir;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync('file_watcher_test_');
    });

    tearDown(() {
      if (tempDir.existsSync()) {
        tempDir.deleteSync(recursive: true);
      }
    });

    testWidgets('fileExists returns true when file exists', (tester) async {
      final file = File('${tempDir.path}/existing.txt')
        ..writeAsStringSync('test');

      await tester.pumpWidget(
        MaterialApp(
          home: _TestWidget(path: file.path),
        ),
      );

      final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
      expect(state.fileExists, isTrue);
    });

    testWidgets('fileExists returns false when file does not exist', (
      tester,
    ) async {
      final path = '${tempDir.path}/nonexistent.txt';

      await tester.pumpWidget(
        MaterialApp(
          home: _TestWidget(path: path),
        ),
      );

      final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
      expect(state.fileExists, isFalse);
    });

    testWidgets('resetFileWatcher allows re-checking same path', (
      tester,
    ) async {
      final file = File('${tempDir.path}/test.txt');
      final path = file.path;

      await tester.pumpWidget(
        MaterialApp(
          home: _TestWidget(path: path),
        ),
      );

      final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
      expect(state.fileExists, isFalse);

      // Create the file
      file.writeAsStringSync('test');

      // Reset and re-check
      state
        ..resetFileWatcher()
        ..setupFileWatcher(path);

      expect(state.fileExists, isTrue);
    });

    testWidgets(
      'picks up a file written after the initial check without a manual '
      'reset (regression: a one-shot check loses this race for content '
      'that finishes writing moments after the widget mounts, e.g. '
      'AI-generated cover art)',
      (tester) async {
        final path = '${tempDir.path}/generated.png';

        await tester.pumpWidget(
          MaterialApp(home: _TestWidget(path: path)),
        );
        expect(find.text('not exists'), findsOneWidget);

        // The file lands on disk after the widget has already mounted and
        // performed its first (negative) check.
        File(path).writeAsStringSync('generated bytes');

        // Advance through the bounded poll without ever calling
        // setupFileWatcher again — the widget must pick this up on its own.
        await tester.pump(const Duration(milliseconds: 150));

        expect(find.text('exists'), findsOneWidget);
      },
    );

    testWidgets(
      'gives up after the bounded poll budget if the file never appears',
      (tester) async {
        final path = '${tempDir.path}/never-written.png';

        await tester.pumpWidget(
          MaterialApp(home: _TestWidget(path: path)),
        );

        // Exhaust the full poll budget (20 attempts * 100ms) with room to
        // spare; the timer must have canceled itself, not spun forever.
        await tester.pump(const Duration(milliseconds: 2500));

        expect(find.text('not exists'), findsOneWidget);
      },
    );

    testWidgets('disposeFileWatcher can be called safely', (tester) async {
      final path = '${tempDir.path}/test.txt';

      await tester.pumpWidget(
        MaterialApp(
          home: _TestWidget(path: path),
        ),
      );

      tester.state<_TestWidgetState>(find.byType(_TestWidget))
        // Should not throw
        ..disposeFileWatcher()
        ..disposeFileWatcher(); // Double dispose should be safe
    });

    testWidgets('setupFileWatcher is idempotent for same path', (tester) async {
      final file = File('${tempDir.path}/test.txt')..writeAsStringSync('test');

      await tester.pumpWidget(
        MaterialApp(
          home: _TestWidget(path: file.path),
        ),
      );

      final state = tester.state<_TestWidgetState>(find.byType(_TestWidget))
        // Call multiple times - should not cause issues
        ..setupFileWatcher(file.path)
        ..setupFileWatcher(file.path)
        ..setupFileWatcher(file.path);

      expect(state.fileExists, isTrue);
    });

    testWidgets('setupFileWatcher with forceReset rechecks same path', (
      tester,
    ) async {
      final path = '${tempDir.path}/force_reset_test.txt';

      await tester.pumpWidget(
        MaterialApp(
          home: _TestWidget(path: path),
        ),
      );

      final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
      expect(state.fileExists, isFalse);

      // Create the file
      File(path).writeAsStringSync('test');

      // Without forceReset, same path would not be rechecked
      // Use forceReset to force recheck
      state.setupFileWatcher(path, forceReset: true);

      expect(state.fileExists, isTrue);
    });

    testWidgets('setupFileWatcher switches to new path correctly', (
      tester,
    ) async {
      final file1 = File('${tempDir.path}/file1.txt')
        ..writeAsStringSync('test1');
      final path2 = '${tempDir.path}/file2.txt';

      await tester.pumpWidget(
        MaterialApp(
          home: _TestWidget(path: file1.path),
        ),
      );

      final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
      expect(state.fileExists, isTrue);

      // Switch to a non-existent path
      state.setupFileWatcher(path2);
      expect(state.fileExists, isFalse);

      // Create the second file and reset
      File(path2).writeAsStringSync('test2');
      state
        ..resetFileWatcher()
        ..setupFileWatcher(path2);
      expect(state.fileExists, isTrue);
    });

    testWidgets('handles non-existent parent directory gracefully', (
      tester,
    ) async {
      final path = '${tempDir.path}/nonexistent_dir/file.txt';

      await tester.pumpWidget(
        MaterialApp(
          home: _TestWidget(path: path),
        ),
      );

      final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
      // Should handle missing parent directory without crashing
      expect(state.fileExists, isFalse);
    });
  });

  group('pathsEqual', () {
    test('returns true for identical paths', () {
      expect(pathsEqual('/foo/bar/file.txt', '/foo/bar/file.txt'), isTrue);
    });

    test('returns false for different paths', () {
      expect(pathsEqual('/foo/bar/file.txt', '/foo/baz/file.txt'), isFalse);
    });

    test('normalizes paths with redundant separators', () {
      expect(pathsEqual('/foo//bar/file.txt', '/foo/bar/file.txt'), isTrue);
    });

    test('normalizes paths with . components', () {
      expect(pathsEqual('/foo/./bar/file.txt', '/foo/bar/file.txt'), isTrue);
    });

    test('normalizes paths with .. components', () {
      expect(
        pathsEqual('/foo/baz/../bar/file.txt', '/foo/bar/file.txt'),
        isTrue,
      );
    });

    test('handles mixed forward and back slashes', () {
      // On non-Windows, backslashes are literal characters in paths.
      // On Windows, they're path separators.
      // This test verifies normalization handles this correctly.
      final path1 = p.join('foo', 'bar', 'file.txt');
      final path2 = p.join('foo', 'bar', 'file.txt');
      expect(pathsEqual(path1, path2), isTrue);
    });

    test('handles trailing separators consistently', () {
      // Directories with and without trailing separators
      expect(
        pathsEqual('/foo/bar/', '/foo/bar'),
        // Note: p.normalize keeps trailing separator for directories
        // but the paths should still compare correctly for files
        isTrue,
      );
    });

    test('handles relative paths by making them absolute', () {
      // Both paths should be made absolute before comparison
      final currentDir = Directory.current.path;
      const relativePath = 'test.txt';
      final absolutePath = p.join(currentDir, 'test.txt');
      expect(pathsEqual(relativePath, absolutePath), isTrue);
    });

    test('case sensitivity depends on platform', () {
      // On Windows, paths are case-insensitive
      // On Unix-like systems, paths are case-sensitive
      const path1 = '/foo/bar/File.txt';
      const path2 = '/foo/bar/file.txt';

      if (Platform.isWindows) {
        expect(pathsEqual(path1, path2), isTrue);
      } else {
        expect(pathsEqual(path1, path2), isFalse);
      }
    });

    test('handles Windows-style paths with backslashes on Windows', () {
      // This test is more meaningful on Windows, but should not break on other platforms
      if (Platform.isWindows) {
        expect(
          pathsEqual(r'C:\Users\test\file.txt', r'C:\Users\test\file.txt'),
          isTrue,
        );
        expect(
          pathsEqual(r'C:\Users\test\file.txt', 'C:/Users/test/file.txt'),
          isTrue,
        );
        // Case insensitivity on Windows
        expect(
          pathsEqual(r'C:\Users\Test\FILE.txt', r'C:\Users\test\file.txt'),
          isTrue,
        );
      }
    });

    test('handles paths with spaces', () {
      expect(
        pathsEqual('/foo/bar baz/file.txt', '/foo/bar baz/file.txt'),
        isTrue,
      );
    });

    test('handles paths with special characters', () {
      expect(
        pathsEqual('/foo/bar-baz_123/file.txt', '/foo/bar-baz_123/file.txt'),
        isTrue,
      );
    });
  });

  // ---------------------------------------------------------------------------
  // Non-test-env code paths (lines 36–57 of file_watcher_mixin.dart)
  // These tests temporarily set isTestEnv = false so that setupFileWatcher
  // exercises the real watcher logic instead of the synchronous test shortcut.
  // ---------------------------------------------------------------------------
  group('FileWatcherMixin – non-test-env paths', () {
    late Directory tempDir;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync('file_watcher_nontest_');
    });

    tearDown(() {
      if (tempDir.existsSync()) {
        tempDir.deleteSync(recursive: true);
      }
    });

    testWidgets(
      'same-path guard: second call with same path is a no-op (line 36)',
      (tester) async {
        final path = '${tempDir.path}/guard_test.txt';

        platform_utils.isTestEnv = false;
        addTearDown(() => platform_utils.isTestEnv = true);

        await tester.pumpWidget(MaterialApp(home: _TestWidget(path: path)));

        final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
        expect(state.fileExists, isFalse);

        // A second call with the same path must hit the early-return guard and
        // leave fileExists unchanged.
        state.setupFileWatcher(path);
        expect(state.fileExists, isFalse);
      },
    );

    testWidgets(
      'file already exists: sets fileExists=true and returns (lines 42-44)',
      (tester) async {
        final file = File('${tempDir.path}/exists_nontest.txt')
          ..writeAsStringSync('data');

        platform_utils.isTestEnv = false;
        addTearDown(() => platform_utils.isTestEnv = true);

        await tester.pumpWidget(
          MaterialApp(home: _TestWidget(path: file.path)),
        );

        final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
        expect(state.fileExists, isTrue);
        expect(find.text('exists'), findsOneWidget);
      },
    );

    testWidgets(
      'non-existent file in existing dir: sets fileExists=false (line 48)',
      (tester) async {
        final path = '${tempDir.path}/not_yet.txt';

        platform_utils.isTestEnv = false;
        addTearDown(() => platform_utils.isTestEnv = true);

        await tester.pumpWidget(MaterialApp(home: _TestWidget(path: path)));

        final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
        expect(state.fileExists, isFalse);
        expect(find.text('not exists'), findsOneWidget);
      },
    );

    testWidgets(
      'non-existent parent directory: returns early without watcher (lines 51-52)',
      (tester) async {
        final path = '${tempDir.path}/missing_dir/file.txt';

        platform_utils.isTestEnv = false;
        addTearDown(() => platform_utils.isTestEnv = true);

        await tester.pumpWidget(MaterialApp(home: _TestWidget(path: path)));

        final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
        // Parent dir does not exist → early return, no crash, fileExists = false.
        expect(state.fileExists, isFalse);
      },
    );

    testWidgets(
      'switching to a new path disposes old watcher and rechecks (lines 39-40)',
      (tester) async {
        final file1 = File('${tempDir.path}/first.txt')
          ..writeAsStringSync('first');
        final path2 = '${tempDir.path}/second.txt';

        platform_utils.isTestEnv = false;
        addTearDown(() => platform_utils.isTestEnv = true);

        await tester.pumpWidget(
          MaterialApp(home: _TestWidget(path: file1.path)),
        );

        final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
        expect(state.fileExists, isTrue);

        // Switch to a new (non-existent) path – exercises _disposeWatcher +
        // _watchedPath assignment (lines 39-40) and then lines 42-48.
        state.setupFileWatcher(path2);
        expect(state.fileExists, isFalse);
      },
    );

    testWidgets(
      'forceReset re-executes setup for the same path (bypasses line 36 guard)',
      (tester) async {
        final path = '${tempDir.path}/force.txt';

        platform_utils.isTestEnv = false;
        addTearDown(() => platform_utils.isTestEnv = true);

        await tester.pumpWidget(MaterialApp(home: _TestWidget(path: path)));

        final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
        expect(state.fileExists, isFalse);

        // Create the file, then force-reset so the watcher re-reads existence.
        File(path).writeAsStringSync('hello');
        state.setupFileWatcher(path, forceReset: true);
        expect(state.fileExists, isTrue);
      },
    );

    testWidgets(
      'file-creation event fires watcher callback and sets fileExists=true '
      '(lines 54-57)',
      (tester) async {
        final path = '${tempDir.path}/watched.txt';

        platform_utils.isTestEnv = false;
        addTearDown(() => platform_utils.isTestEnv = true);

        await tester.pumpWidget(MaterialApp(home: _TestWidget(path: path)));

        final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
        expect(state.fileExists, isFalse);

        // runAsync allows real OS-level async I/O events (inotify) to be
        // delivered. We create the file inside runAsync so that the resulting
        // FileSystemEvent from dir.watch() can reach the stream listener.
        await tester.runAsync(() async {
          File(path).writeAsStringSync('hello');
          // Give the OS a moment to emit the inotify event and let the Dart
          // event loop process it.
          await Future<void>.delayed(const Duration(milliseconds: 200));
        });

        // Pump Flutter frames so setState(() => _fileExists = true) is applied.
        await tester.pump();

        expect(state.fileExists, isTrue);
        expect(find.text('exists'), findsOneWidget);
      },
    );
  });

  // ---------------------------------------------------------------------------
  // Platforms without a directory watch. iOS throws a FileSystemException
  // from Directory.watch(); before the poll fallback that exception left the
  // build and became a 100 000 px ErrorWidget in every demo cover slot while
  // the catalog downloaded. IOOverrides plays the OS here.
  // ---------------------------------------------------------------------------
  group('FileWatcherMixin – no directory watch available', () {
    late Directory tempDir;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync('file_watcher_poll_');
      platform_utils.isTestEnv = false;
    });

    tearDown(() {
      platform_utils.isTestEnv = true;
      if (tempDir.existsSync()) {
        tempDir.deleteSync(recursive: true);
      }
    });

    /// Runs [body] where the OS reports no watch support, as iOS does.
    Future<void> withoutWatchSupport(Future<void> Function() body) =>
        IOOverrides.runZoned(body, fsWatchIsSupported: () => false);

    testWidgets('polls for the file instead of watching, and finds it', (
      tester,
    ) async {
      final path = '${tempDir.path}/downloading.webp';

      await withoutWatchSupport(() async {
        await tester.pumpWidget(MaterialApp(home: _TestWidget(path: path)));
        final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
        expect(state.fileExists, isFalse);
        expect(find.text('not exists'), findsOneWidget);

        File(path).writeAsStringSync('bytes');
        await tester.pump(const Duration(milliseconds: 999));
        expect(find.text('not exists'), findsOneWidget);

        await tester.pump(const Duration(milliseconds: 1));
        expect(state.fileExists, isTrue);
        expect(find.text('exists'), findsOneWidget);
      });
    });

    testWidgets('stops polling after its budget, and stops looking', (
      tester,
    ) async {
      final path = '${tempDir.path}/never.webp';

      await withoutWatchSupport(() async {
        await tester.pumpWidget(MaterialApp(home: _TestWidget(path: path)));
        await tester.pump(const Duration(seconds: 1800));

        // Budget spent: a file arriving now is not noticed until a rebuild,
        // and — checked by the test framework at teardown — no timer is left
        // ticking for a file that never came.
        File(path).writeAsStringSync('late');
        await tester.pump(const Duration(seconds: 5));
        final state = tester.state<_TestWidgetState>(find.byType(_TestWidget));
        expect(state.fileExists, isFalse);
      });
    });

    testWidgets('a poll in flight is cancelled with the widget', (
      tester,
    ) async {
      final path = '${tempDir.path}/abandoned.webp';

      await withoutWatchSupport(() async {
        await tester.pumpWidget(MaterialApp(home: _TestWidget(path: path)));
        await tester.pump(const Duration(seconds: 3));

        await tester.pumpWidget(const MaterialApp(home: SizedBox()));

        // Would fail with "A Timer is still pending" otherwise.
        await tester.pump(const Duration(seconds: 3));
        expect(find.byType(_TestWidget), findsNothing);
      });
    });

    testWidgets('falls back to polling when the watch itself is refused', (
      tester,
    ) async {
      final path = '${tempDir.path}/refused.webp';

      await IOOverrides.runZoned(
        () async {
          await tester.pumpWidget(MaterialApp(home: _TestWidget(path: path)));
          final state = tester.state<_TestWidgetState>(
            find.byType(_TestWidget),
          );
          expect(state.fileExists, isFalse);
          expect(tester.takeException(), isNull);

          File(path).writeAsStringSync('bytes');
          await tester.pump(const Duration(seconds: 1));
          expect(state.fileExists, isTrue);
        },
        fsWatch: (_, _, _) => throw const FileSystemException(
          'File system watching is not supported on this platform',
        ),
      );
    });

    testWidgets('falls back to polling when the watch stream errors', (
      tester,
    ) async {
      final path = '${tempDir.path}/lost_watch.webp';

      await IOOverrides.runZoned(
        () async {
          await tester.pumpWidget(MaterialApp(home: _TestWidget(path: path)));
          // Let the error reach the subscription.
          await tester.pump();
          final state = tester.state<_TestWidgetState>(
            find.byType(_TestWidget),
          );
          expect(state.fileExists, isFalse);
          expect(tester.takeException(), isNull);

          File(path).writeAsStringSync('bytes');
          await tester.pump(const Duration(seconds: 1));
          expect(state.fileExists, isTrue);
        },
        fsWatch: (_, _, _) => Stream<FileSystemEvent>.error(
          const FileSystemException('watch descriptor dropped'),
        ),
      );
    });

    testWidgets('cancels the errored watch it falls back from', (
      tester,
    ) async {
      final path = '${tempDir.path}/errored_watch.webp';
      var cancelled = false;
      final watch = StreamController<FileSystemEvent>(
        onCancel: () => cancelled = true,
      );
      addTearDown(() => unawaited(watch.close()));

      await IOOverrides.runZoned(
        () async {
          await tester.pumpWidget(MaterialApp(home: _TestWidget(path: path)));
          expect(cancelled, isFalse);

          // An error does not close a stream; a subscription left behind
          // would outlive the widget with nothing able to cancel it.
          watch.addError(const FileSystemException('watch dropped'));
          await tester.pump();
          expect(cancelled, isTrue);

          File(path).writeAsStringSync('bytes');
          await tester.pump(const Duration(seconds: 1));
          final state = tester.state<_TestWidgetState>(
            find.byType(_TestWidget),
          );
          expect(state.fileExists, isTrue);
        },
        fsWatch: (_, _, _) => watch.stream,
      );
    });

    testWidgets('a watch error reaching an unmounted state starts no poll', (
      tester,
    ) async {
      final path = '${tempDir.path}/gone.webp';
      final errors = StreamController<FileSystemEvent>();
      addTearDown(() => unawaited(errors.close()));

      await IOOverrides.runZoned(
        () async {
          // A widget that never calls disposeFileWatcher keeps its
          // subscription past its own lifetime; the error must not start a
          // poll for a state that is gone.
          await tester.pumpWidget(
            MaterialApp(home: _ForgetfulTestWidget(path: path)),
          );
          await tester.pumpWidget(const MaterialApp(home: SizedBox()));

          errors.addError(const FileSystemException('late error'));
          await tester.pump();

          expect(tester.takeException(), isNull);
          File(path).writeAsStringSync('bytes');
          // No timer fires (the test framework fails a pending one at
          // teardown), and nothing tries to setState on the dead widget.
          await tester.pump(const Duration(seconds: 2));
        },
        fsWatch: (_, _, _) => errors.stream,
      );
    });
  });
}

/// Test widget that uses the FileWatcherMixin
class _TestWidget extends StatefulWidget {
  const _TestWidget({required this.path});

  final String path;

  @override
  State<_TestWidget> createState() => _TestWidgetState();
}

class _TestWidgetState extends State<_TestWidget> with FileWatcherMixin {
  @override
  void initState() {
    super.initState();
    setupFileWatcher(widget.path);
  }

  @override
  void dispose() {
    disposeFileWatcher();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Text(fileExists ? 'exists' : 'not exists');
  }
}

/// A [FileWatcherMixin] user that forgets [FileWatcherMixin.disposeFileWatcher].
class _ForgetfulTestWidget extends StatefulWidget {
  const _ForgetfulTestWidget({required this.path});

  final String path;

  @override
  State<_ForgetfulTestWidget> createState() => _ForgetfulTestWidgetState();
}

class _ForgetfulTestWidgetState extends State<_ForgetfulTestWidget>
    with FileWatcherMixin {
  @override
  void initState() {
    super.initState();
    setupFileWatcher(widget.path);
  }

  @override
  Widget build(BuildContext context) {
    return Text(fileExists ? 'exists' : 'not exists');
  }
}
