import 'package:lotti/features/categories/domain/category_icon.dart';

/// Human-readable display name for every [CategoryIcon].
const Map<CategoryIcon, String> categoryIconDisplayNames = {
  CategoryIcon.fitness: 'Fitness',
  CategoryIcon.running: 'Running',
  CategoryIcon.swimming: 'Swimming',
  CategoryIcon.yoga: 'Yoga',
  CategoryIcon.nutrition: 'Nutrition',
  CategoryIcon.water: 'Water',
  CategoryIcon.dining: 'Dining',
  CategoryIcon.medical: 'Medical',
  CategoryIcon.medication: 'Medication',
  CategoryIcon.heartHealth: 'Heart Health',
  CategoryIcon.heartPulse: 'Heart Rate',
  CategoryIcon.sleep: 'Sleep',
  CategoryIcon.bedtime: 'Bedtime',
  CategoryIcon.mood: 'Mood',
  CategoryIcon.mindfulness: 'Mindfulness',
  CategoryIcon.mentalHealth: 'Mental Health',
  CategoryIcon.checklist: 'Checklist',
  CategoryIcon.assignment: 'Assignment',
  CategoryIcon.clipboard: 'Tasks',
  CategoryIcon.work: 'Work',
  CategoryIcon.meeting: 'Meeting',
  CategoryIcon.laptop: 'Computer Work',
  CategoryIcon.home: 'Home',
  CategoryIcon.cleaning: 'Cleaning',
  CategoryIcon.chores: 'Chores',
  CategoryIcon.shopping: 'Shopping',
  CategoryIcon.groceries: 'Groceries',
  CategoryIcon.store: 'Store',
  CategoryIcon.commute: 'Commute',
  CategoryIcon.car: 'Driving',
  CategoryIcon.transit: 'Public Transit',
  CategoryIcon.reading: 'Reading',
  CategoryIcon.writing: 'Writing',
  CategoryIcon.journal: 'Journal',
  CategoryIcon.school: 'Education',
  CategoryIcon.brain: 'Learning',
  CategoryIcon.learning: 'Study',
  CategoryIcon.people: 'Social',
  CategoryIcon.relationships: 'Relationships',
  CategoryIcon.social: 'Groups',
  CategoryIcon.gaming: 'Gaming',
  CategoryIcon.music: 'Music',
  CategoryIcon.art: 'Art',
  CategoryIcon.photography: 'Photography',
  CategoryIcon.wallet: 'Wallet',
  CategoryIcon.money: 'Money',
  CategoryIcon.savings: 'Savings',
  CategoryIcon.location: 'Location',
  CategoryIcon.travel: 'Travel',
  CategoryIcon.airplane: 'Flight',
  CategoryIcon.schedule: 'Schedule',
  CategoryIcon.calendar: 'Calendar',
  CategoryIcon.timer: 'Timer',
  CategoryIcon.phone: 'Phone',
  CategoryIcon.computer: 'Computer',
  CategoryIcon.connectivity: 'Internet',
  CategoryIcon.baby: 'Baby',
  CategoryIcon.cycling: 'Cycling',
  CategoryIcon.hiking: 'Hiking',
  CategoryIcon.camping: 'Camping',
  CategoryIcon.pets: 'Pets',
  CategoryIcon.garden: 'Gardening',
  CategoryIcon.cooking: 'Cooking',
  CategoryIcon.coffee: 'Coffee',
  CategoryIcon.email: 'Email',
  CategoryIcon.chat: 'Chat',
  CategoryIcon.videoCall: 'Video Call',
  CategoryIcon.movie: 'Movies',
  CategoryIcon.podcast: 'Podcast',
  CategoryIcon.theater: 'Theater',
  CategoryIcon.coding: 'Coding',
  CategoryIcon.crafts: 'Crafts',
  CategoryIcon.dance: 'Dance',
  CategoryIcon.laundry: 'Laundry',
  CategoryIcon.repair: 'Repair',
  CategoryIcon.banking: 'Banking',
  CategoryIcon.investment: 'Investment',
  CategoryIcon.receipt: 'Receipt',
  CategoryIcon.celebration: 'Celebration',
  CategoryIcon.gift: 'Gift',
  CategoryIcon.cake: 'Birthday',
  CategoryIcon.language: 'Language',
  CategoryIcon.science: 'Science',
  CategoryIcon.presentation: 'Presentation',
  CategoryIcon.prayer: 'Prayer',
  CategoryIcon.gratitude: 'Gratitude',
  CategoryIcon.spa: 'Self-Care',
  CategoryIcon.stretching: 'Stretching',
  CategoryIcon.weather: 'Weather',
  CategoryIcon.nature: 'Nature',
  CategoryIcon.volunteer: 'Volunteering',
  CategoryIcon.recycling: 'Recycling',
};
