name: lotti
version: 0.8.248
summary: Lotti - a smart digital assistant
description: Manage your life, privacy first

confinement: strict
base: core22
grade: stable

slots:
  dbus-lotti:
    interface: dbus
    bus: session
    name: com.matthiasnehlsen.lotti

apps:
  lotti:
    command: lotti
    extensions: [flutter-stable]
    plugs:
      - network
    slots:
      - dbus-lotti
parts:
  lotti:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
    - libsecret-1-0
    - libsecret-1-dev
    - libjsoncpp-dev
    - libkeybinder-3.0-dev
