name: Android
on: [push]

jobs:
  build:
    name: Build APK
    runs-on: macOS-latest
    if: github.ref == 'refs/heads/android-release'
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Set up gradle.properties
        run: echo "$GRADLE_PROPERTIES" | base64 -D > ~/.gradle/gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      - name: Set up android keystore
        run: echo "$ANDROID_KEYSTORE" | base64 -D > ~/.android/android-release-key.keystore
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install shadow-cljs
        run: npm install -g shadow-cljs
      - name: Release
        working-directory: MeinsApp
        run: make android
      - uses: actions/upload-artifact@master
        with:
          name: release-apk
          path: MeinsApp/android/app/build/outputs/apk/release/app-release.apk
