name: Build Flatpak

permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  flatpak:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for git describe

    - name: Install Flatpak and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder

        # Add Flathub repository
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

        # Install required runtime and SDK
        sudo flatpak install -y flathub org.freedesktop.Platform//24.08
        sudo flatpak install -y flathub org.freedesktop.Sdk//24.08
        sudo flatpak install -y flathub org.freedesktop.Sdk.Extension.llvm20//24.08
        sudo flatpak install -y flathub org.freedesktop.Sdk.Extension.rust-stable//24.08

    - name: Update manifest with current commit
      run: |
        # Update the manifest commit placeholder with the current SHA
        cd flatpak
        ./update_manifest_commit.sh ${{ github.sha }}

        # Show the updated manifest
        echo "Manifest updated with commit ${{ github.sha }}:"
        grep -A2 "url: https://github.com/matthiasn/lotti" com.matthiasn.lotti.source.yml

    - name: Build Flatpak
      run: |
        cd flatpak
        flatpak-builder --verbose --force-clean --repo=repo build-dir com.matthiasn.lotti.source.yml

    - name: Create Flatpak bundle
      run: |
        cd flatpak
        flatpak build-bundle repo lotti.flatpak com.matthiasn.lotti

    - name: Upload Flatpak bundle
      uses: actions/upload-artifact@v4
      with:
        name: lotti-flatpak-${{ github.sha }}
        path: flatpak/lotti.flatpak
        retention-days: 30