name: Flutter Test (self-hosted, very_good)

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Flutter Test on Linux (self-hosted, very_good)
    permissions:
      contents: read
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: kuhnroyal/flutter-fvm-config-action@v2 
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Get dependencies
        run: flutter pub get
      - name: Activate very_good_cli
        run: dart pub global activate very_good_cli
      - name: Run Flutter tests
        run: very_good test --coverage
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: matthiasn/lotti
