name: Flutter Windows

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Flutter Build on Windows
    runs-on: windows-latest
    steps:
      - name: core.symlinks
        run: |
          git config --global core.symlinks true
      - name: Support long paths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel: 'stable'
      - name: Flutter Doctor
        run: make doctor
      - name: Flutter get dependencies
        run: flutter pub get
      - name: Flutter generate l10n
        run: flutter gen-l10n
      - name: Flutter build
        run: flutter build windows
      - name: Flutter create MSIX
        run: flutter pub run msix:create
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/windows/runner/Release/lotti.msix
