name: Flutter Android GitHub Release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Flutter Build Android on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.2'
          channel: 'stable'
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install libraries
        run: sudo apt-get install libgtk-3-dev cmake cmake-doc ninja-build libsecret-1-dev libjsoncpp-dev libjsoncpp1 libsecret-1-0 sqlite3 libsqlite3-dev keybinder-3.0
      - name: Flutter Doctor
        run: make doctor
      - name: Create GitHub Release
        run: gh release create -p --generate-notes --target $GITHUB_SHA $GITHUB_REF_NAME || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: make clean_test
      - name: Build
        run: make android
      - name: Bundle
        run: bundletool build-apks --mode universal --bundle build/app/outputs/bundle/release/app-release.aab --output build/android/lotti.apks --overwrite
      - name: Rename
        run: cp build/android/lotti.apks build/android/lotti.zip
      - name: Unzip
        run: cd build/android && unzip lotti.zip && cd -
      - name: Upload apk to GitHub Releases
        run: gh release upload $GITHUB_REF_NAME build/android/universal.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload aab to GitHub Releases
        run: gh release upload $GITHUB_REF_NAME build/app/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
