name: Fluttium Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Fluttium Test on Windows
    runs-on: windows-latest
    steps:
      - name: core.symlinks
        run: |
          git config --global core.symlinks true
      - name: Support long paths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.10.0'
            channel: 'stable'
      - run: flutter config --enable-windows-desktop
      - name: Activate Fluttium
        run: flutter pub global activate fluttium_cli
      - name: Run Fluttium tests
        run: fluttium test test_flows/habit_flow.yaml --reporter expanded
