name: Flutter Linux Build

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Flutter Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Test and build
        working-directory: ./lotti
        run: make linux
