name: Flutter Matrix Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Matrix Test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install libraries
        run: sudo apt-get install libgtk-3-dev cmake libolm3 cmake-doc ninja-build libsecret-1-dev libjsoncpp-dev libsecret-1-0 sqlite3 libsqlite3-dev keybinder-3.0 network-manager mpv libmpv-dev
      - uses: actions/checkout@v3
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          cwd: "integration_test/docker"
      - name: Run Matrix integration test
        uses: GabrielBB/xvfb-action@v1.7
        env:
          SLOW_NETWORK: false
        with:
          working-directory: ./integration_test
          run: |
            ./setup_toxiproxy_docker.sh
            ./run_matrix_tests.sh

  test_degraded_network:
    name: Matrix Test on Linux with degraded network
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install libraries
        run: sudo apt-get install libgtk-3-dev cmake libolm3 cmake-doc ninja-build libsecret-1-dev libjsoncpp-dev libsecret-1-0 sqlite3 libsqlite3-dev keybinder-3.0 network-manager mpv libmpv-dev
      - uses: actions/checkout@v3
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          cwd: "integration_test/docker"
      - name: Run Matrix integration test
        uses: GabrielBB/xvfb-action@v1.6
        env:
          SLOW_NETWORK: true
        with:
          working-directory: ./integration_test
          run: |
            ./setup_toxiproxy_docker.sh
            ./run_matrix_tests.sh
