name: Flutter Windows

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Fluttium on Windows
    runs-on: windows-latest
    steps:
      - name: core.symlinks
        run: |
          git config --global core.symlinks true
      - name: Support long paths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
          channel: 'stable'
      - name: Flutter Doctor
        run: make doctor
      - name: Flutter get dependencies
        run: flutter pub get
      - name: Flutter generate l10n
        run: flutter gen-l10n
      - name: Flutter build
        run: flutter build windows
      - name: Flutter activate Fluttium
        run: flutter pub global activate fluttium_cli
      - name: Run Fluttium
        run: fluttium test test_flows/habit_flow.yaml --flavor production --target lib/main.dart
