name: Flutter Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Flutter Test on Linux
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install libraries
        run: sudo apt-get install network-manager libmpv-dev
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: kuhnroyal/flutter-fvm-config-action@v2 
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Get dependencies
        run: flutter pub get
      - name: Run Flutter tests
        run: flutter test --coverage --reporter=compact
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: matthiasn/lotti
