name: Flutter Matrix Integration Test

on:
  push:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Matrix Test on Linux
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev cmake libolm3 cmake-doc ninja-build libsecret-1-dev libjsoncpp-dev libsecret-1-0 sqlite3 libsqlite3-dev keybinder-3.0 network-manager mpv libmpv-dev
          version: 1.0
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Cache Pub Packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          cwd: "integration_test/docker"
      - name: Run Matrix integration tests
        uses: GabrielBB/xvfb-action@v1.6
        env:
          SLOW_NETWORK: false
        with:
          working-directory: ./integration_test
          run: |
            chmod +x ./setup_toxiproxy_docker.sh ./run_matrix_tests.sh
            ./setup_toxiproxy_docker.sh
            ./run_matrix_tests.sh

  test_degraded_network:
    name: Matrix Test on Linux with degraded network
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev cmake libolm3 cmake-doc ninja-build libsecret-1-dev libjsoncpp-dev libsecret-1-0 sqlite3 libsqlite3-dev keybinder-3.0 network-manager mpv libmpv-dev
          version: 1.0
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          cwd: "integration_test/docker"
      - name: Run Matrix integration tests (degraded)
        uses: GabrielBB/xvfb-action@v1.6
        env:
          SLOW_NETWORK: true
        with:
          working-directory: ./integration_test
          run: |
            chmod +x ./setup_toxiproxy_docker.sh ./run_matrix_tests.sh
            ./setup_toxiproxy_docker.sh
            ./run_matrix_tests.sh
