name: Flutter Linux

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Flutter Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.1'
          channel: 'stable'
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install libraries
        run: sudo apt-get install libgtk-3-dev cmake cmake-doc ninja-build libsecret-1-dev libjsoncpp-dev libsecret-1-0 sqlite3 libsqlite3-dev keybinder-3.0 network-manager
      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop
      - name: Flutter Doctor
        run: make doctor
      - name: Test and build
        run: make linux
      - uses: actions/upload-artifact@v2
        with:
          name: lotti
          path: ./lotti/build/linux/x64/release/bundle/lotti
