name: Fluttium Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Fluttium Test on macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
            architecture: x64
      - run: flutter config --enable-macos-desktop
      - name: Run l10n codegen
        run: make l10n
      - name: Activate Fluttium
        run: make activate_fluttium
      - name: Run Fluttium tests
        run: make fluttium_linux
