name: Build & Release

on:
  push:
    branches:
      - master

jobs:

  build-release-linux:
    name: Build & Release Linux
    runs-on: ubuntu-latest
    steps:
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: Check leiningen version
        run: lein -v
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup build dependencies
        run: make deps-ubuntu
      - name: Test & Build
        run: make install
      - name: Publish via GitHub Releases
        run: make publish-github
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}


  build-release-macos:
    name: Build & Release macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Retrieve certificate
        run: echo "$DEV_CERT" | base64 -D > Certificates.p12
        env:
          DEV_CERT: ${{ secrets.DEV_CERT }}
      - name: Set up keychain
        run: |
          security create-keychain -p ${{ secrets.KEYCHAIN_PW }} build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p ${{ secrets.KEYCHAIN_PW }} build.keychain
          security import Certificates.p12 -k ~/Library/Keychains/build.keychain -P ${{ secrets.DEV_CERT_PW }} -A
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${{ secrets.KEYCHAIN_PW }} build.keychain
        env:
          DEV_CERT: ${{ secrets.DEV_CERT }}
          DEV_CERT_PW: ${{ secrets.DEV_CERT_PW }}
          KEYCHAIN_PW: ${{ secrets.KEYCHAIN_PW }}
      - name: List identities
        run: security find-identity -v
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: Check leiningen version
        run: lein -v
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup build dependencies
        run: make deps-mac
      - name: Test & Build
        run: make install
      - name: Publish via GitHub Releases
        run: make publish-github
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_LINK: Certificates.p12
          CSC_KEY_PASSWORD: ${{ secrets.DEV_CERT_PW }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}


  build-release-windows:
    name: Build & Release Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup build dependencies
        run: |
          choco install make -y --no-progress
          choco install lein -y --no-progress
          choco install python2 -y --no-progress
          npm set progress=false
          npm install -g shadow-cljs
          npm install -g windows-build-tools@4.0.0
          npm install -g node-gyp
          npm install -g electron-builder
          npm install -g electron-rebuild
        shell: pwsh
      - name: Test & Build
        run: make install
      - name: Publish via GitHub Releases
        run: make publish-github
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}


  build-release-ios-nightly:
    name: Build & Release on TestFlight - Nightly
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Clone mailcore
        working-directory: ../
        run: git clone https://github.com/MailCore/mailcore2.git
      - name: Git setup
        run: git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: Fastlane match certificates
        working-directory: MeinsApp/ios
        run: fastlane certificates
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_PW: ${{ secrets.KEYCHAIN_PW }}
      - name: Install iOS Distribution certificate
        run: |
          echo "$IOS_DISTRIBUTION_CERT" | base64 -D > ios_distribution.p12
          security import ios_distribution.p12 -k ~/Library/Keychains/fastlane.keychain -P ${{ secrets.DEV_CERT_PW }} -A
        env:
          IOS_DISTRIBUTION_CERT: ${{ secrets.IOS_DISTRIBUTION_CERT }}
          DEV_CERT_PW: ${{ secrets.DEV_CERT_PW }}
          KEYCHAIN_PW: ${{ secrets.KEYCHAIN_PW }}
      - name: List identities
        run: |
          security list-keychains
          security find-identity -v fastlane.keychain
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install shadow-cljs
        run: npm install -g shadow-cljs
      - name: Release
        working-directory: MeinsApp
        run: make testflight-nightly
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
