name: Release meins
on: [push]

jobs:
  mac:
    name: Release macOS
    runs-on: macOS-latest
    steps:
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: Check leiningen version
        run: lein -v
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup build dependencies
        run: make deps-mac
      - name: Retrieve certificate
        run: echo "$DEV_CERT" | base64 -D > Certificates.p12
        env:
          DEV_CERT: ${{ secrets.DEV_CERT }}
      - name: Release
        run: make release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_LINK: Certificates.p12
          CSC_KEY_PASSWORD: ${{ secrets.DEV_CERT_PW }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}

  linux:
    name: Release Linux
    runs-on: ubuntu-latest
    steps:
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: Check leiningen version
        run: lein -v
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup build dependencies
        run: make deps-ubuntu
      - name: Release
        run: make release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
