name: Linux
on: [push]

jobs:
  build:
    name: Build & Release Linux
    runs-on: ubuntu-latest
    steps:
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: Check leiningen version
        run: lein -v
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup build dependencies
        run: make deps-ubuntu
      - name: Release
        run: make release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
