name: Build & Release Desktop

on:
  push:
    branches:
      - master

jobs:

  build-release-linux:
    name: Build & Release Linux
    runs-on: ubuntu-latest
    steps:
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: Check leiningen version
        run: lein -v
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup build dependencies
        run: make deps-ubuntu
      - name: Test & Build
        run: make install
      - name: Publish via GitHub Releases
        run: make publish-github
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}


  build-release-macos:
    name: Build & Release macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Retrieve certificate
        run: echo "$DEV_CERT" | base64 -D > Certificates.p12
        env:
          DEV_CERT: ${{ secrets.DEV_CERT }}
      - name: Set up keychain
        run: |
          security create-keychain -p ${{ secrets.KEYCHAIN_PW }} build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p ${{ secrets.KEYCHAIN_PW }} build.keychain
          security import Certificates.p12 -k ~/Library/Keychains/build.keychain -P ${{ secrets.DEV_CERT_PW }} -A
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${{ secrets.KEYCHAIN_PW }} build.keychain
        env:
          DEV_CERT: ${{ secrets.DEV_CERT }}
          DEV_CERT_PW: ${{ secrets.DEV_CERT_PW }}
          KEYCHAIN_PW: ${{ secrets.KEYCHAIN_PW }}
      - name: List identities
        run: security find-identity -v
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: Check leiningen version
        run: lein -v
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup build dependencies
        run: make deps-mac
      - name: Test & Build
        run: make install
      - name: Publish via GitHub Releases
        run: make publish-github
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_LINK: Certificates.p12
          CSC_KEY_PASSWORD: ${{ secrets.DEV_CERT_PW }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}


  build-release-windows:
    name: Build & Release Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup build dependencies
        run: |
          choco install make -y
          choco install lein -y
          choco install python2 -y
          npm set progress=false
          npm install -g shadow-cljs
          npm install -g windows-build-tools@4.0.0
          npm install -g node-gyp
          npm install -g electron-builder
          npm install -g electron-rebuild
        shell: pwsh
      - name: Test & Build
        run: make install
      - name: Publish via GitHub Releases
        run: make publish-github
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
