name: Test & Build Desktop

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:

  test-build-linux:
    name: Test & Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: Check leiningen version
        run: lein -v
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup build dependencies
        run: make deps-ubuntu
      - name: Test & Build
        run: make


  test-build-macos:
    name: Test & Build macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
      - name: Check leiningen version
        run: lein -v
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup build dependencies
        run: make deps-mac
      - name: Test & Build
        run: make test cljs-shared-tests cljs


  test-build-windows:
    name: Test & Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup build dependencies
        run: |
          choco install make -y
          choco install lein -y
          choco install python2 -y
          npm install -g shadow-cljs
          npm install -g windows-build-tools@4.0.0
          npm install -g node-gyp
          npm install -g electron-builder
          npm install -g electron-rebuild
        shell: pwsh
      - name: Test & Build
        run: make
